### ISSUE TITLE
Fork eeditiones/tei-publisher-vscode plugin

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#101]
Per #98, please fork https://github.com/eeditiones/tei-publisher-vscode

There's a bit of additional documentation here: https://e-editiones.org/vscode/

Maybe you'd want to fork it first in the srophe org, then fork that in the usaybia repo?

**Comment by nathangibson** [comment]
@wsalesky Now that the API is up and running, does that mean we're ready to start adapting the plugin?

**Comment by wsalesky** [comment]
Yes, I started look at the plugin yesterday.

**Comment by nathangibson** [comment]
Excited
