### ISSUE TITLE
Install VS Code extensions

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#104]
@usaybia/mitarbeit Some of you may already have some of these installed. These will help make our further work more efficient. 
You can install them by clicking on the link and then clicking install. Or they will also be listed as "recommended" extensions (along with others) if you open the usaybia-data folder in VS Code and then open the extensions pane in the left sidebar. 
- https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
- https://marketplace.visualstudio.com/items?itemName=github.vscode-pull-request-github
- https://marketplace.visualstudio.com/items?itemName=raffazizzi.sxml
- https://marketplace.visualstudio.com/items?itemName=e-editiones.tei-publisher-vscode
- https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml

Check beside your name when done. The last person can close the issue.

- [x] @MalindaT 
- [x] @lunadine 
- [x] @FlavioZeska 
- [x] @hannafriedel

**Comment by lunadine** [comment]
perfect, thanks for looking for these!
