### ISSUE TITLE
Install VSC Plugin for Usaybia

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#109]
**Important: Please uninstall the general (marketplace) TEI Publisher plugin before doing this.**

This is a plugin that searches Usaybia.net for people/places we want to tag. 

Download it by clicking on https://github.com/usaybia/tei-publisher-vscode/raw/master/tei-publisher-vscode-1.0.0.vsix (or go [here](https://github.com/usaybia/tei-publisher-vscode/blob/master/tei-publisher-vscode-1.0.0.vsix) if that doesn't work).

Then in VS Code, click the Extensions button > ... > Install from VSIX and select the file you downloaded. (See screenshot.) You may have to reload VS Code before it will be active.

**To use:** 

1.  Click the TEI Publisher button in the sidebar 
2. Open a TEI file and select the name to search for. 
3. Press Cmd-Shift-E or Ctrl-Shift-E
4. Press the + button beside the correct name to add the element with the correct URI.

- [x] @MalindaT 
- [x] @lunadine 
- [x] @hannafriedel 
- [x] @FlavioZeska 

<img width="903" alt="Screen Shot 2021-02-22 at 10 53 20 AM" src="https://user-images.githubusercontent.com/3083452/108692550-0a1aab80-74fd-11eb-9384-047b2259ae2e.png">
<img width="903" alt="Screen Shot 2021-02-22 at 10 55 05 AM" src="https://user-images.githubusercontent.com/3083452/108692566-0edf5f80-74fd-11eb-93c7-77e3ab834a91.png">

**Comment by MalindaT** [comment]
Hey Nathan thanks again a lot for the extension. I downloaded it but somehow it doesnt find anything (not in english, not in arabic). Do you know what could be the reason for this?

**Comment by nathangibson** [comment]
@MalindaT Hmm, it seems to be working for me right now. Can you give some examples what you're searching for? 

When you open the sidebar, in the dropdown do you see a list that says "All, Places - Srophe, People - Srophe," etc.? (screenshot 1)

If you use the search bar to search for something common like "Muhammad" do you get results? (screenshot 2)

<img width="366" alt="Screen Shot 2021-02-25 at 12 41 36 PM" src="https://user-images.githubusercontent.com/3083452/109148835-0db16b00-7767-11eb-8f3f-ec27e6300318.png">
<img width="366" alt="Screen Shot 2021-02-25 at 12 40 29 PM" src="https://user-images.githubusercontent.com/3083452/109148852-143fe280-7767-11eb-8886-2af77f7f7bb1.png">

**Comment by hannafriedel** [comment]
Works for me, too!
