### ISSUE TITLE
Add relevant bibliography from Ptolemaeus and EI3

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#11]
This issue is just for reference so that you can look at the details.

We are interested in 
 1. Editions and translations of Ibn Abi Usaybia's work
 2. General studies about the work 
 3. Studies about people appearing in IAU's text, particularly biographical information, editions or clavici of their works, and information about their personal networks. (We can exclude studies about the content of particular texts written by these people.)

In addition to importing items from Ptolemaeus, please also add the bibliography items listed in the EI3 article at http://dx.doi.org.emedien.ub.uni-muenchen.de/10.1163/1573-3912_ei3_COM_30677.

**Comment by nathangibson** [comment]
Just to document our discussion so far:
@lunadine Please continue as before with adding these, but we will reassess in early 2020 whether we should continue importing all of these categories (1-3 above) from Ptolemaeus. It might be that for (3) we want only clavici and general biographical items of people and works mentioned in IAU but not all editions/translations of mentioned works or discussions of all biographical details.

**Comment by lunadine** [comment]
For the sake of clarity I created a list of the tags which we currently use in Zotero (together with a short description of when to apply these tags). This is a preliminary list, feel free to comment on it (such as: „do we need this tag? Please delete“ .. or “better rename in xy“)
https://docs.google.com/spreadsheets/d/1uPjaclVe9tFND5ZoyiBX3xkcEhhl6BvUvGsESk9BezY/edit?usp=sharing

While working on our DigLib for the Pre-Pub. some questions came up and I did not find a solution to these in the guidelines. Maybe you have some ideas of how it would be best to solve these:

1) How would you like to indicate italic characteristics in the titles of works? Do we use (““) instead? In PAL we used „\emph“    e.g.  „The Strategy of Revision in the Arabic-Latin Translations from Toledo: The Case of Abū Ma‘shar’s \emph{On the Great Conjunctions}“

2) Is there a way to further specify the ISBN (print, hardcover, softcover vs. online) which one of 
these would you like us to indicate in the ISBN field ?

3) Do we give info in the „Language field“ and if so, do we write „english“ or abbr. „en“ (I was thinking we should only do this in case it is not obvious, like „Urdu“, „Sanskrit" or „Russian“

4) Where would you like to indicate that there exists reprints and reviews to one entry. Maybe in „extra“ or in „notes?"

5) I sometimes have difficulty with the fields: Author/Translator/ Editor 
In many cases these studies are published by several authors and I often cannot tell easily who of them worked on which part of the publication. Also, if we only indicate „Translator“ and „Editor“ but the publication is also a study/research on the treatise, do you think we are depriving the authors of this work? For example: „A Critical Edition of Ibn al-Haytham’s On the Shape of the Eclipse: The First Experimental Study of the Camera Obscura“

6)  For Journal Articles: We give the title of the journal in the field „series“ (e.g. Revue d’Histoire des Sciences) and the short version on  Journal abbr. (e.g. RHS) , correct? 
(see configuration of the universe)

all of this has no hurry, I keep entering new articles in the meantime
thanks a lot

**Comment by nathangibson** [comment]
Thanks so much @lunadine . These are great questions. We can discuss some of them today if you're able to Skype in, and you're right we need to document them.

**Comment by nathangibson** [comment]
1. You can use the emph code. 
 2. Just one ISBN is enough if that's all you have. If you have more than one just separate them with a space.
 3. See 3.11.1 in https://github.com/biblia-arabica/arabic-bible-bibliography/blob/master/documentation/BiAr_Manual.pdf. I will add this to the documentation later.

**Comment by nathangibson** [comment]
3 (cont.) We always want to include the language of the content. 
 4. Please see 3.2 in https://github.com/biblia-arabica/arabic-bible-bibliography/blob/master/documentation/BiAr_Manual.pdf. But enter in the "Extra" field instead of "Abstract" using the format "Reprint: {link}" or "Review: {link}"

**Comment by nathangibson** [comment]
4 (cont.) But only include reviews when they're really important for the history of research. Reprints probably only for editions.
 5. You don't need to create an "author" field if there's already an editor. Put the person in twice as "editor" and "translator" if it's an edition & translation.
 6. Journal title goes in "Publication." We don't need journal abbreviations but we do want DOIs and ISSNs.

**Comment by nathangibson** [comment]
On reprints, let me clarify. Our purpose is simply to help people find the resources that we point to, not to be a comprehensive bibliography. We should include at most 2 entries:
1. An entry for the original item, including a link to open-access if available (e.g., archive.org for older items, MENADoc) 
2a. If the original is _not_ available open-access *but* a reprint is, then also include an entry for the reprint with a link.
2b. If no open-access version is available, then please include an entry for the most recent printing (in addition to the original printing), but not the reprints in-between.
Does this make sense?

**Comment by lunadine** [comment]
Thanks so much for your detailed comments on the bibliography!

**Comment by nathangibson** [comment]
I am reassigning the portion from the EI3 article to @vanessa612 so that she can start working on the bibliography. You can continue with the PAL items.

**Comment by nathangibson** [comment]
@lunadine Are there any items you've entered that you'd like @vanessa612 to check?

**Comment by lunadine** [comment]
@vanessa612: everything contained in the "Pre-pub" file can be checked. (Thank you!)
@nathangibson: the cite keys for the books and articles I had entered in the first months manually have a strange format and I can for some reason not change the keys so that they align with the new ones

**Comment by nathangibson** [comment]
@vanessa612 When you've checked an item, please add a tag with your Zotero username: "Checked: YourUserName". Then it will automatically be added to the "Publish" folder.

**Comment by nathangibson** [comment]
@lunadine I think the BetterBibTex extension has automatically generated Cite Keys for ones that didn't have them yet (i.e., for the ones you entered manually rather than imported). 
If you add the line "Citation Key: ..." in the "Extra" field, it will automatically change the Cite key. 
But there might be other tags that BBT puts in the Extra field that you want to get, too, right? Like who entered it and which person it relates to? In that case you could reimport those items from BibTex and then merge the imported ones with the manually entered ones, making sure to keep the "Extra" field from the imported item. It will keep any tags you entered manually.

**Comment by lunadine** [comment]
@nathangibson:  and apparently then declare the newly imported file with the correct key to the master version. Works well, thanks!

**Comment by nathangibson** [comment]
@lunadine  I think we can close this, right?

**Comment by lunadine** [comment]
Yes, I added the most relevant literature from PAL, there might be some more in future though... but let's close it for now

**Comment by nathangibson** [comment]
Thanks!
