### ISSUE TITLE
xQuery Tutorial

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#114]
@hannafriedel 
Please start learning xQuery doing the following. After you finish this, I can give you some real assignments to build. 

- [x] [XPath tutorial](https://www.w3schools.com/xml/xpath_intro.asp)
- [x] [XQuery tutorial](https://www.w3schools.com/xml/xquery_intro.asp)

For experimenting with XQuery you could either download [Oxygen XML Editor](https://www.oxygenxml.com/) and use the free trial and write xQueries there or write them in eXist in the eXide app. You will have this if you install and run our docker packages and go to http://localhost:8080/exist/apps/eXide/index.html. We can meet sometime and I can show you either of these options.

**Comment by hannafriedel** [comment]
Hi Nathan, do you have time before or after our team meeting on monday?

**Comment by hannafriedel** [comment]
Hi Nathan, after reading the tutorials you provided, I still had a lot of questions. I am currently watching these Youtube Videos, which helps me a lot. I hope this is ok.
https://www.youtube.com/watch?v=O41tUq1_Q1I&list=PL00tNNzES0Df1j3jDb9s6u_FS4hv650d7&index=9

**Comment by nathangibson** [comment]
Yes of course!!
