### ISSUE TITLE
Update version number for all records using xQuery

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#115]
- [x] Make a new branch based on development
- [x] Use the version number from /expath-pkg.xml `/package/@version` to update all TEI files in data/ (including bibl, factoids, persons, places, texts) with this version number. The version number to update is in `/teiHeader/fileDesc/editionStmt/edition/@n`. If some files give errors because they are invalid XML you can exclude/ignore these.

The update extension used by eXist is documented here: http://exist-db.org/exist/apps/doc/update_ext.xml

I would guess you would do `update insert ...` new edition element then `update delete ...` old edition element.

- [x] Export/synchronize the updated files however you like and commit changes to your branch.
- [x] Create a pull request from your branch to development.

**Comment by hannafriedel** [comment]
Hi Nathan, where should I save my file when I use eXide? I thought I could just download what I have written, but it requires me to save it inside the usaibiya repository.

**Comment by nathangibson** [comment]
@hannafriedel Oh, you mean your xquery file? To work with it temporarily you can just create your own folder in exist in /db/apps and save it there. Inside exist it doesn't really matter where you save it.

To save it to Github and keep track of your changes you can put it in copy the code and paste it into a file (or download the file after saving it in exist) and put it in https://github.com/usaybia/usaybia-tools/tree/master/tools/xquery

**Comment by hannafriedel** [comment]
Hi Nathan, I tried for some time now and something very basic doesn't work. I have code  but i cannot really try if it works. Maybe we could talk again before or after our weekly meeting.

**Comment by nathangibson** [comment]
@hannafriedel ok, no problem, it can be tricky. Let’s talk after the team meeting.

**Comment by hannafriedel** [comment]
Hi Nathan. I was too confident, when I told you that I would have solved the issue by the end of this week. I have my code structure down, but have run into problems, which I cannot solve on my own (regarding namespaces). It would be great if we could speak on monday again.

**Comment by hannafriedel** [comment]
Hi Nathan, I finished the XQuery and uploaded it to my branch "update-version-number". It changes the version number only in persons/tei because the other categories do not feature version numbers.
I do not really know how to do the third step (Export/synchronize the updated files however you like and commit changes to your branch) in a timely manner. I can only download one file at a time in exide, so I would have to download each of the approx. 2500 xml files and then reupload them to this branch?
I took a look at how to integrate this XQuery in our workflow and it seems that our best bet is to create our own JSON action which accesses the XQuery file. How did you integrate the other XQuerys (https://github.com/usaybia/usaybia-tools/tree/master/tools/xquery)?

**Comment by nathangibson** [comment]
Export is in eXide through Application > Synchronize. One of the data files must already be open for this to work.

Please add the following:

1. The version number should be updated for all XML files, but it must test first to see whether edition already exists in the file and only update those.
2. Please update the date (`currentDate()`?) in `TEI/teiHeader/fileDesc/publicationStmt/date`

I'll check about workflow options and whether this xQuery should be integrated into Srophe.

**Comment by hannafriedel** [comment]
Hi @nathangibson please take a look at the file usaybia-data/update-version-number-and-date.xquery. It now includes what we just wrote together + I automated the date as well. It works great for me, if you want to test it with your docker, you need to change @version in line 15 to @n.

**Comment by nathangibson** [comment]
@hannafriedel I think I figured out the problem. Maybe it wasn't `update delete` directly but indirectly ... My eXist container in Docker was running out of memory. The default is 512 MB but I needed to increase it to 1024 MB with `docker run -it -d  -m 1024m ...  ` 

Anyway, it seems to work perfectly now! I'll merge this in soon, just need to make a couple tweaks first ...

By the way, if you want to monitor memory usage in eXist, you can open the Monex app from the dashboard. Very handy.
