### ISSUE TITLE
Tag people and places in LHOM chapter 10

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#118]
@MalindaT The lhom-ar-10 file should be up to date in the branch tag-names-with-URIs-/-Robin-Schmahl-27th-May-2020 :-)

**Comment by nathangibson** [comment]
@hannafriedel I've copied here the relevant points from #37:

Here is a list of person name tags with URIs, sorted according to where they occur in Ibn Abi Usaybia (according to the LHOM index): https://github.com/usaybia/usaybia-data/blob/master/data/texts/tei/lhom-person-list.xml

We'll use this to tag the names of people who appear in Chapter 15, biographies 1-49: https://github.com/usaybia/usaybia-data/blob/master/data/texts/tei/lhom-ar-15.xml

If the person appears more than once in a paragraph, we only need to tag them once per paragraph. 

We should also tag 
1. People mentioned by title or pronoun but not by name ("he" or "the caliph") 
2. People we don't have URIs for (we'll mark it as a name and then generate the URI later).


Clarifications for future reference:
 1. Please tag people mentioned in an `<item>` (list item) _even if_ the same person was mentioned in a previous item.
 2. If someone is referenced in a paragraph only by title or pronoun, please use `<rs>` with the appropriate URI in the ref attribute. 
 3. _But_ if a pronoun/title in a paragraph refers to person who is the topic of the entry (e.g. al-Farabi in 15.1), you don't need to tag it.

What about personal suffixes, shall I also tag them? E.g. the ī of ḥadaṯanī in line 134 which refers to IAU.
Another question: How about Farabi's father who is only referenced as Abuhu in the first paragraph of 15? Theoretically speaking, we should also tag him, right?
Correct, we want to tag him, also with rs. We might be able to guess at his name from al-Farabi's name, but it is a bit dangerous since "ibn" can skip generations ... So in the spreadsheet for new URIs we can add a description like "Father of al-Farabī" if his name isn't definitively given.

One more thing: I see that many of the URIs we'll be creating for unnamed people will be identified using their relationship to another person. Instead of copying the Arabic text into the "Arabic description" column such as أبوه, you can create the description in Arabic if you feel confident doing so, e.g., أبو أبي نصر الفارابي. If you don't feel confident about it you can leave it blank and just include it in English. This is not meant to be a quotation but just an identifying description. I've also added columns for "relationship" and "related person" and filled in the ones you've done as an example.

Section 15.3.2 starts with an اقول meaning IAU says - should I tag the whole verb as rs and put IAU as reference?
When he's using it simply as "authorial style," then no, but if he's explicitly putting himself into an isnād then yes.

When you have anonymous people who are described in the text, you can use a short identifiable description to create the URI. See examples here http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?keyword=anonymous

For future reference: URIs should be created for groups if they are specifically identifiable groups (and also mark the Group column in the New Persons spreadsheet)
It appears that the Ikhwān al-Ṣafāʾ do not have a URI yet although they are mentioned in the spreadsheet (between URIs 1217 and 1216) - shouldn't they have a URI or how should I tag them then? (e.g. in section 15.1.4)
Ikhwan al-Safa is more like an affiliation than a specifically identifiable group that we could create a URI for. And in this case the reference itself is uncertain.

When there is a person you don't have a URI for, you can add them here: https://docs.google.com/spreadsheets/d/1ujiT91ua3sA-WX86OWpuE-gDD_E-zONpI1dP70pXdWw/edit#gid=813408100 in the "New Persons" tab (copy the next URI from cell A2)

I think I figured out a way to tag things consistently in VSC. It acts differently if the Arabic is in the middle of Arabic text or is between left-to-right text. But if you leave an extra space on each side of the Arabic text you want to tag, you can add line breaks in either situation. 

I suggest adding a double line break so that you have 1 empty line where you can paste the start tag and 1 empty line to paste the end tag. (See screenshots.) Hope this helps!

<img width="908" alt="Screen Shot 2020-11-23 at 3 16 08 PM" src="https://user-images.githubusercontent.com/3083452/99973320-edf15c00-2d9f-11eb-8c67-4a82c935fbda.png">
<img width="908" alt="Screen Shot 2020-11-23 at 3 20 29 PM" src="https://user-images.githubusercontent.com/3083452/99973339-f21d7980-2d9f-11eb-8e65-9457e2b07926.png">
<img width="908" alt="Screen Shot 2020-11-23 at 3 22 51 PM" src="https://user-images.githubusercontent.com/3083452/99973342-f34ea680-2d9f-11eb-951e-56686957974e.png">

**Comment by MalindaT** [comment]
As we have to tag places in Chapter 10 I would like to ask where I can make URIs for places which can not be found. E.g. in Cahpter 10.3.7. it says: Thābit was once walking with al-Muʿtaḍid in al-Firdaws, which was a garden in the Caliph’s palace intended for exercise....

**Comment by nathangibson** [comment]
Yes, you're right. New places can be added in this spreadsheet https://docs.google.com/spreadsheets/d/1B6vJjZjUbCX-oyqmrgVmVq7GmyqvaAjfBlzcIYnwhpQ/edit#gid=1970039361 in the tab "NewPlaces". To get the URI for the new place, please copy it from cell A2.

**Comment by nathangibson** [comment]
@MalindaT By the way, ch. 10 is the longest chapter. Ch. 15 is almost as long , ch. 14 a bit shorter, and all other chapters are much shorter. Actually I think ch. 10 might be about 1/3 of the whole book!
