### ISSUE TITLE
Clean up Transkribus layout in Mueller vol. 2b

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#12]
@MalindaT Can you please start from the beginning of Mueller volume 2b in Transkribus and clean up the layout for the whole document, page-by-page? We need to do this before doing the text recognition and transcription so that Transkribus doesn't try to interpret random lines or marks and so that we can separate the page numbers, headers, etc. from the regular text.

I've written detailed instructions in the "Cleaning up the Layout" section of this Wiki page: 
https://github.com/usaybia/usaybia-data/wiki/Transcription-of-Sources-from-Page-Images#cleaning-up-the-layout

I have also done the first 4 pages as an example of what is correct. 

I think this will go quickly once you get used to it, but it might also be an annoying task. If you hate this assignment after doing 50 pages or so, let me know and we will try to rotate so that other people work on it too! :-)

**Comment by nathangibson** [comment]
@MalindaT As you go please make sure the text regions are also separated. The page number should be 1 text region, the page content inside the black box another, and the catchword a third. (Also individual text regions for each header in the margin.) 
If you need to split text regions you can use the scissor tools. To change the size you can click on the region until it turns green, then move the edge. To add a text region, click the "+TR" button.
Make sense?

**Comment by nathangibson** [comment]
Related: #17

**Comment by nathangibson** [comment]
@MalindaT I wanted to do some testing with Transkribus so I made some slight changes to page images 2-5 of file 2b. 
 1. I made the page numbers and catchwords separate text regions by using the H scissors tool. 
 2. Where there was a header in the margin and a new biography begins I also split the main text region at that point using the H scissors so that the header could come at the correct place in the text (header 1, text 1, header 2, text 2, etc.). Then I used the "layout" tab to drag things into the correct order. See page 4 as an example. I'm sorry I didn't realize before that we needed to do this -- I know it's new. But I think the text will be in the wrong order unless we do it.

**Comment by nathangibson** [comment]
@MalindaT How is this going? It looks like you've gotten to page 37 or so?

**Comment by MalindaT** [comment]
Hello, yes im currently working further on it. Actually I was finished, then I just realised yesterday that I understood something wrong (the order of the text fields) and I just have to apply the new text fields. Im so sorry! 
    Am Dienstag, 26. November 2019, 11:46:21 MEZ hat nathangibson <notifications@github.com> Folgendes geschrieben:  
 
 
@MalindaT How is this going? It looks like you've gotten to page 37 or so?

**Comment by nathangibson** [comment]
No problem! The pace is fine, I just wanted to find out the status.

**Comment by nathangibson** [comment]
@MalindaT This looks excellent!! Thank you.
I'm running the text recognition now on those pages and will give you a Word document you can use for comparing and correcting the two versions.
