### ISSUE TITLE
Identifying  الملك الانكور

### ISSUE THREAD

**Issue by RobinSchmahl** [usaybia/usaybia-data#13]
Hi everybody,

While going through the first Recogito file again, I came across "الملك الانكور". I don't find this guy in the Index and am unable to identify him.
Any ideas?

Best, Robin

**Comment by nathangibson** [comment]
I'm not great with poetry and I haven't read the whole context, but it's possible it's not a name. "The king" and then a word (though I haven't been able to find this word either). 

The word or name could be corrupted. Once we are working with the new edition or one of the manuscripts, we can check that.

Another possibility is that it's a foreign name. 

Other ideas? 

No worries if we don't figure it out yet. You can leave it tagged as a person and I will do some more checking when I go through that part of the text.

**Comment by RobinSchmahl** [comment]
OK.

I've thought about that as well, but I didn't find anything in the dictionaries (Lane, Wehr, Lisan al-Arab). 
So I'll leave it with a short comment.

Thanks!
