### ISSUE TITLE
Check person names in Recogito (Mueller 2:239-274)

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#14]
@RobinSchmahl Besides checking if there are any person names we missed, can you please also 
 1. Remove the "person" category from items tagged "occupational-descriptor" and "relational-descriptor" if these are not part of a name. (You can do this by clicking the trash icon beside "Marked as a person." It should keep the tag, just not the person classification.)
 2. Make sure each tagged person has an Usaybia.net URI (create one if needed, see #5).
Thanks!

**Comment by nathangibson** [comment]
@RobinSchmahl When you get a chance please let me know the status of this.

**Comment by RobinSchmahl** [comment]
I think I've got everybody, so it should be finished!

**Comment by nathangibson** [comment]
Wonderful!
