### ISSUE TITLE
Factoids for Authorial Manuscript Copies  

### ISSUE THREAD

**Issue by lunadine** [usaybia/usaybia-data#147]
Finish "reader of handwriting of" factoids and try visualisation

**Comment by lunadine** [comment]
@nathangibson - done, needs to be checked and distributed in corresponding files

**Comment by nathangibson** [comment]
@lunadine What we did in https://github.com/usaybia/usaybia-data/commit/c8f1842c4 was adequate, right? I believe you just needed to double-check that the factoid numbers/factoid URIs worked correctly, right?

**Comment by lunadine** [comment]
@nathangibson exactly, I checked these entries, and our XQuery worked well, I didn't spot any problems.
