### ISSUE TITLE
Test transcription comparison using Microsoft Word

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#18]
@MalindaT Can you please test this process for comparing the Shamela transcription with the automatic transcription from Transkribus? 

Here is a Word document that shows the differences between the two versions. https://github.com/usaybia/usaybia-data/blob/master/data/texts/transkribus/IU-mueller-1884-vol2b_2-5.docx

And here are the instructions for what to do with it: https://github.com/usaybia/usaybia-data/wiki/Comparing-downloaded-text-to-HTR-text-in-a-Microsoft-Word-document

@lunadine You might want to take a look at this too since maybe you will have some ideas and it will be the same process you'll use for your section.

**Comment by lunadine** [comment]
Wow thank you for creating this detailed guide for teaching us

**Comment by nathangibson** [comment]
@MalindaT Have you had a chance to try this process yet?
