### ISSUE TITLE
Correction: Word separation

### ISSUE THREAD

**Issue by chiarampohl** [usaybia/usaybia-data#203]
### URI of the page with the mistake

https://usaybia.net/person/53

### What should be corrected on the page?

The Arabic headword is split while English headword is written together

### How should it be corrected?

? 

### Public Acknowledgement

Yes

**Comment by nathangibson** [comment]
This is a Syriac name written together in Syriac: the English headword should be 
ʿAbdishoʿ bar Bahrīz 

Besides this, "al-ʿAbdī" on the beginning was a mistake (was duplicated from the line above on the spreadsheet). 

I've corrected these in the spreadsheet and added an alternative form with a space in between.
