### ISSUE TITLE
Clean up Transkribus layout in Mueller vol. 2a, images 14-end (pages 5-end)

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#22]
@MalindaT Can you please do the same cleanup process you did for vol. 2b for vol. 2a, images 14-end (pages 5-end)? Thanks!

**Comment by MalindaT** [comment]
Hey I am right now starting with page 14. I dont understand exactly what you mean with (pages 5-end)? 2a from page 14 until page 146? Or just 5 pages until 119?

**Comment by MalindaT** [comment]
Hey, alright I started a few hours ago :) What does (pages 5-end) exactly mean?

**Comment by MalindaT** [comment]
Also I have a question concerning the order of the headers/notes on the side. 
On page 32 in 2a there is on the left side something written which is not a header. In which order it has to be? 

![image](https://user-images.githubusercontent.com/46726275/71322472-26215800-24c8-11ea-8148-11b7f5718668.png)

**Comment by nathangibson** [comment]
@MalindaT So sorry I was already off email and didn't see your message until just now. 

Yes I meant all pages starting with page 5 (which is image 14).

**Comment by nathangibson** [comment]
@MalindaT On image 32 I agree, this is not a regular header. I don't immediately see how or where it relates to the text. We will have to figure out the details later. 
For now, please split the main text region after line 6-21 and order the text region on the left side between the new text regions, the same as you would for a header. Then mark the text in the left with structure type > other.
