### ISSUE TITLE
Create preliminary vocabulary for Ibn Ridwan factoids

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#29]
@lunadine You're already doing this but I wanted to create an issue here so that we can track this. 

By the way, I think the following is the most up-to-date schema for SPEAR. You can paste the following lines at the top of your TEI file and Oxygen will tell you in the error messages about the proper format for each factoid. The only thing is that some things are "hard-wired" for SPEAR or Syriaca.org so we'll need to make our own schema later to adapt those. 

```
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/SPEARschema/out/SPEAR.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/SPEARschema/out/SPEAR.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

**Comment by lunadine** [comment]
Okay perfect; here is the link to the file in which I currently collect, keywords and factoids
https://docs.google.com/spreadsheets/d/1E4Jqcq9gzgsmTOitiBYrf7m0tfIcswN1Td357s96VJ8/edit#gid=0
and this is the file in which I started to collect some questions/problems on the factoids; but we can also collect them here in Guthub
https://docs.google.com/document/d/1y43WvWth_fyAGWslZXm8tCkBXLBaycG-n1wsggPE7KI/edit

**Comment by nathangibson** [comment]
Per conversation with @dlschwartz keywords to be added to Syriac taxonomy can be put in the "To Transform" sheet of the Syriaca "Taxonomy" spreadsheet: https://docs.google.com/spreadsheets/d/14jU8K-hjFH193zsqXzrdYPYfx2HFqttX0TPScdsbukA/edit#gid=1713223714 

@lunadine Please let me know each time you add new keywords. When we do we should go ahead and change the prefix in your spreadsheet from "usaybia:" to "syriaca:"

@dlschwartz Can you at message us using the Google Sheet 

See also #40
