### ISSUE TITLE
Enter relationship keywords for LHOM Index

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#35]
In the [LHOM Index Spreadsheet, Relations tab](https://docs.google.com/spreadsheets/d/1ujiT91ua3sA-WX86OWpuE-gDD_E-zONpI1dP70pXdWw/edit#gid=731012579), please go through row-by-row and add relationship keywords "son of", "sister of", etc. in the Add New Keywords column. Copy-paste values for the "Suggested Relation Keywords", "Relation Name", and "Relation Person URI" to confirm these are correct. Sometimes you'll have to search for the right person and insert the URI manually. Or sometimes you'll have to select that the related thing is not a person but a group, a place, etc. or that we don't have a URI for that person. 

Please see the attached screenshot for more details. 

Note: The relationship keywords are usually phrases including "of", "to", or "from", such as "physician to" or "daughter of". Make sure to include the preposition :-) 

It's a big job, so perhaps you'll want help at some point or to take a break!

<img width="1860" alt="Bildschirmfoto 2020-05-13 um 16 28 39" src="https://user-images.githubusercontent.com/3083452/81828569-38189b80-953a-11ea-9eca-2a2157650190.png">

**Comment by nathangibson** [comment]
@MalindaT I also added @FafLam to this task. If you're working on it at the same time I'll leave it to you two to decide who does which rows :-)

**Comment by nathangibson** [comment]
@MalindaT @FafLam Just wanted to add a couple clarifications regarding the relations. 

1. The type "work" refers to a literary work (like _The Almagest_), not a profession. We're not recording professions/occupations like "physician" here _unless_ it is a relation, i.e., "physician _to_" or "physician _of_." I've corrected these. (See screenshot for some examples of the type of thing I've corrected.) An exception could be something like "Cordovan vizier" which would become the relationship "vizier of ... Cordova ... place"

2. _All_ new keywords should be added in Column E "Add New Keywords." In columns F "Relation 1" and P "Relation 2" etc., you only need to change something if the relationship label is not extracted correctly. 

3. Please confirm the following columns (when the cell is not blank) by copying and pasting values (Cmd/Ctrl-Shift-V): D "Suggested Relation Keywords," G/Q/AA/AK "Relation Name," and N/X/AH/AR "Relation Person URI". These will turn **white** once you do that. 

Thanks! I know this is a very detailed assignment!

<img width="941" alt="Screen Shot 2020-05-19 at 12 19 48 PM" src="https://user-images.githubusercontent.com/3083452/82321393-0fc6ec00-99d5-11ea-8bac-72c4a1b09e51.png">

**Comment by nathangibson** [comment]
Please remove from Column E (Add new keywords) all keywords that should not be automatically recognized for all rows (e.g. physician, poet) and correct in Column D. When you have a keyword that should only be recognized once you can put it in D.

**Comment by MalindaT** [comment]
Hey Nathan, ich habe eine Frage, oft kommen bei Relations so welche Sachen vor 

![image](https://user-images.githubusercontent.com/46726275/85229242-e68ce780-b3e8-11ea-9039-38583a403013.png)



Dort steht dann z.B. dass es um den Neffen/Frau oder Tante von jemand Bekannten geht. Für diese gibt es oft aber keine Namen oder URIs, wie mache ich es dann richtig? Weil bei dem Beispiel das ich dir eingefügt habe stimmt es ja dann so eigentlich gar nicht oder? LG

**Comment by nathangibson** [comment]
Ja, gute Frage wir können beim Treffen diskutieren

**Comment by nathangibson** [comment]
Updates on relationship tagging guidelines:
 - "also known as" or aka is not a relationship
 - random letters for scribes like "scribe of S" is not a relationship - these refer to manuscripts
 - "Andalusian physician" is a relationship to Andalusia (or other places)
 - "N/A" error usually means I've deleted the URI and you can skip this one. (You can search in the Text tab to make sure whether there's a URI.)

**Comment by nathangibson** [comment]
Also, when you're not sure of an identification -- whether you have the right person -- you can leave the URI box light green (unconfirmed).

**Comment by nathangibson** [comment]
Note to self: I think this is ready for me to check.
