### ISSUE TITLE
Replace old URIs with new ones

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#36]
@lunadine Would you please replace the old URIs with new ones in Zotero and in any person names you've tagged in your texts? The matching is done or almost done in [this spreadsheet](https://docs.google.com/spreadsheets/u/1/d/1qm4SUeYHBjCn43Wxms1Btn8SbhVEngiiG8h8NxTUjpc/edit#gid=400094632) (see columns D and E) but I've also added the results from there to the [LHOM Index Spreadsheet](https://docs.google.com/spreadsheets/d/1ujiT91ua3sA-WX86OWpuE-gDD_E-zONpI1dP70pXdWw/edit#gid=0), at the end, column AR. 

My suggestion would be to first add "/old" to all URIs in Zotero and your texts, e.g., "https://usaybia.net/person/old/..." Then it will be clear during the process which ones have already been replaced and which still need to be done. 

In Zotero, you can change them by right-clicking the tag > rename tag.

In Oxygen, you can use find/replace:
 1. Replace "usaybia.net/person/" with "usaybia.net/person/old/"
 2. Then you can use the Xpath (in the Xpath Builder panel under Window > Show view) `distinct-values(//persName/@ref[matches(.,"person/old")])` to see which URIs you'll need to replace
 3. Then you can run the find/replace for each of those URIs to replace old URIs with new ones. (But be sure to include the " on the end so that it doesn't also match longer URIs containing that number.)

Or you can do it manually in Oxygen, but the above is good practice :-)

Does this make sense?

**Comment by lunadine** [comment]
done, thanks for the detailed explanation!
