### ISSUE TITLE
Tag names with URIs in LHOM text, 15.1-15.49

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#37]
I'll explain this more when we meet, for now here are some links.

Here is a list of person name tags with URIs, sorted according to where they occur in Ibn Abi Usaybia (according to the LHOM index): https://github.com/usaybia/usaybia-data/blob/master/data/texts/tei/lhom-person-list.xml

We'll use this to tag the names of people who appear in Chapter 15, biographies 1-49: https://github.com/usaybia/usaybia-data/blob/master/data/texts/tei/lhom-ar-15.xml

If the person appears more than once in a paragraph, we only need to tag them once per paragraph. 

We should also tag 
1. People mentioned by title or pronoun but not by name ("he" or "the caliph") 
2. People we don't have URIs for (we'll mark it as a name and then generate the URI later).

**Comment by nathangibson** [comment]
@RobinSchmahl I just corrected the person list and there are a lot more names in it now. Please use the updated version (sync/pull in Github).

**Comment by nathangibson** [comment]
@RobinSchmahl Thanks for the great tagging work! 
Clarifications for future reference:
 1. Please tag people mentioned in an `<item>` (list item) _even if_ the same person was mentioned in a previous item.
 2. If someone is referenced in a paragraph only by title or pronoun, please use `<rs>` with the appropriate URI in the ref attribute. 
 3. _But_ if a pronoun/title in a paragraph refers to person who is the topic of the entry (e.g. al-Farabi in 15.1), you don't need to tag it.

**Comment by RobinSchmahl** [comment]
What about personal suffixes, shall I also tag them? E.g. the ī of ḥadaṯanī in line 134 which refers to IAU.

**Comment by RobinSchmahl** [comment]
Another question: How about Farabi's father who is only referenced as Abuhu in the first paragraph of 15? Theoretically speaking, we should also tag him, right?

**Comment by RobinSchmahl** [comment]
> What about personal suffixes, shall I also tag them? E.g. the ī of ḥadaṯanī in line 134 which refers to IAU.

Nevermind! I saw that you have also tagged a nī with rs. So I'll do the same with the other ones.

**Comment by nathangibson** [comment]
> Another question: How about Farabi's father who is only referenced as Abuhu in the first paragraph of 15? Theoretically speaking, we should also tag him, right?

Correct, we want to tag him, also with rs. We might be able to guess at his name from al-Farabi's name, but it is a bit dangerous since "ibn" can skip generations ... So in the spreadsheet for new URIs we can add a description like "Father of al-Farabī" if his name isn't definitively given. I can show you this when we meet.

**Comment by RobinSchmahl** [comment]
@nathangibson Two short questions regarding the tagging:

1. In section 15.3.1.1 (line 827) appears a certain Abū l-Rajā who is the father of Abū l-Karam. In Arabic it reads: 

.... قال حدثني أبو الكرم الطبيب عن أبيه أبي الرجاء ....

I've now tagged Abū l-Rajā as a persName, however I was wondering whether I should also include the Abihi in the tag or should I tag it separately as rs or leave it out altogether?

2. In the same section appears a certain Abū l-Khayr who has a conversation with "a young boy" (صبي) - shall I also tag the boy and create a URI for him?

Thank you!

**Comment by RobinSchmahl** [comment]
> @nathangibson Two short questions regarding the tagging:
> 
> 1. In section 15.3.1.1 (line 827) appears a certain Abū l-Rajā who is the father of Abū l-Karam. In Arabic it reads:
> 
> .... قال حدثني أبو الكرم الطبيب عن أبيه أبي الرجاء ....
> 
> I've now tagged Abū l-Rajā as a persName, however I was wondering whether I should also include the Abihi in the tag or should I tag it separately as rs or leave it out altogether?
> 
> 1. In the same section appears a certain Abū l-Khayr who has a conversation with "a young boy" (صبي) - shall I also tag the boy and create a URI for him?
> 
> Thank you!

Regarding the second question: I've just read a bit further and it appears that the boy is actually al-Yabrudi (If I am not mistaken) - I guess I shall tag the boy as rs then, right? 

Thank you!

**Comment by nathangibson** [comment]
@RobinSchmahl 
> > 1. In section 15.3.1.1 (line 827) appears a certain Abū l-Rajā who is the father of Abū l-Karam. In Arabic it reads:
> > 
> > .... قال حدثني أبو الكرم الطبيب عن أبيه أبي الرجاء ....
> > I've now tagged Abū l-Rajā as a persName, however I was wondering whether I should also include the Abihi in the tag or should I tag it separately as rs or leave it out altogether?

You can leave out the Abihi. 
> > 
> > 1. In the same section appears a certain Abū l-Khayr who has a conversation with "a young boy" (صبي) - shall I also tag the boy and create a URI for him?
> > 
> > Thank you!
> 
> Regarding the second question: I've just read a bit further and it appears that the boy is actually al-Yabrudi (If I am not mistaken) - I guess I shall tag the boy as rs then, right?

Yes, if you've identified the boy as al-Yabrudi, and if he appears just as "boy" (صبي) in another section, you can tag (صبي) with rs. If it's in the same section you don't need to tag (صبي) at all.

One more thing: I see that many of the URIs we'll be creating for unnamed people will be identified using their relationship to another person. Instead of copying the Arabic text into the "Arabic description" column such as أبوه, you can create the description in Arabic if you feel confident doing so, e.g., أبو أبي نصر الفارابي. If you don't feel confident about it you can leave it blank and just include it in English. This is not meant to be a quotation but just an identifying description.  I've also added columns for "relationship" and "related person" and filled in the ones you've done as an example. 

Thanks!

**Comment by RobinSchmahl** [comment]
> @RobinSchmahl
> 
> > > 1. In section 15.3.1.1 (line 827) appears a certain Abū l-Rajā who is the father of Abū l-Karam. In Arabic it reads:
> > > 
> > > .... قال حدثني أبو الكرم الطبيب عن أبيه أبي الرجاء ....
> > > I've now tagged Abū l-Rajā as a persName, however I was wondering whether I should also include the Abihi in the tag or should I tag it separately as rs or leave it out altogether?
> 
> You can leave out the Abihi.
> 
> > > 1. In the same section appears a certain Abū l-Khayr who has a conversation with "a young boy" (صبي) - shall I also tag the boy and create a URI for him?
> > > 
> > > Thank you!
> > 
> > 
> > Regarding the second question: I've just read a bit further and it appears that the boy is actually al-Yabrudi (If I am not mistaken) - I guess I shall tag the boy as rs then, right?
> 
> Yes, if you've identified the boy as al-Yabrudi, and if he appears just as "boy" (صبي) in another section, you can tag (صبي) with rs. If it's in the same section you don't need to tag (صبي) at all.
> 
> One more thing: I see that many of the URIs we'll be creating for unnamed people will be identified using their relationship to another person. Instead of copying the Arabic text into the "Arabic description" column such as أبوه, you can create the description in Arabic if you feel confident doing so, e.g., أبو أبي نصر الفارابي. If you don't feel confident about it you can leave it blank and just include it in English. This is not meant to be a quotation but just an identifying description. I've also added columns for "relationship" and "related person" and filled in the ones you've done as an example.
> 
> Thanks!

@nathangibson  

Alright, thanks!

**Comment by RobinSchmahl** [comment]
@nathangibson 

Another short question:

Section 15.3.2 starts with an اقول meaning IAU - should I tag the whole verb as rs put IAU as reference?

Thanks!

Robin

**Comment by nathangibson** [comment]
> @nathangibson
> 
> Another short question:
> 
> Section 15.3.2 starts with an اقول meaning IAU says - should I tag the whole verb as rs and put IAU as reference?
> 
> Thanks!
> 
> Robin

When he's using it simply as "authorial style," then no, but if he's explicitly putting himself into an *isnād* then yes.

**Comment by nathangibson** [comment]
When you have anonymous people who are described in the text, you can use a short identifiable description to create the URI. See examples here http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?keyword=anonymous

**Comment by RobinSchmahl** [comment]
@nathangibson 

It appears that the Ikhwān al-Ṣafāʾ do not have a URI yet although they are mentioned in the spreadsheet (between URIs 1217 and 1216) - shouldn't they have a URI or how should I tag them then? (e.g. in section 15.1.4)

Thanks!

**Comment by nathangibson** [comment]
@RobinSchmahl sorry for the slow response. No URI needed. In the spreadsheet we're not including URIs for index entries if we've marked them as a "group" or otherwise not a person. Ikhwan al-Safa is more like an affiliation than a specifically identifiable group that we could create a URI for. And in this case the reference itself is uncertain.

**Comment by nathangibson** [comment]
@RobinSchmahl How is this one going? If you have a long ways to go still we could try the automatic tagging. If it's only a little bit left, you could finish manually.

**Comment by RobinSchmahl** [comment]
@nathangibson I am currently working on 15.13 - so I think using the automatic tagging (in its current state)  would be a great help for continuing this task and speeding up the process. 

btw.: what is the URI for IAU's father? (see my question in slack) We should already have an entry for him, right?

**Comment by nathangibson** [comment]
@RobinSchmahl Great, please keep going manually and I'll do the automatic tagging on it as soon as I can. In the meantime, please make sure you commit your changes in your Github branch and sync them regularly so that when I do the autotagging I am using the most up-to-date version. 

IAU's father is https://usaybia.net/person/1945

**Comment by nathangibson** [comment]
@MalindaT Search is now working on usaybia.net. That is probably easier than searching the LHOM Index spreadsheet.

When there is a person you don't have a URI for, you can add them here: https://docs.google.com/spreadsheets/d/1ujiT91ua3sA-WX86OWpuE-gDD_E-zONpI1dP70pXdWw/edit#gid=813408100 in the "New Persons" tab (copy the next URI from cell A2)

**Comment by nathangibson** [comment]
@MalindaT (@lunadine maybe helpful for you too)

I think I figured out a way to tag things consistently in VSC. It acts differently if the Arabic is in the middle of Arabic text or is between left-to-right text. But if you leave an extra space on each side of the Arabic text you want to tag, you can add line breaks in either situation. 

I suggest adding a double line break so that you have 1 empty line where you can paste the start tag and 1 empty line to paste the end tag. (See screenshots.) Hope this helps!

<img width="908" alt="Screen Shot 2020-11-23 at 3 16 08 PM" src="https://user-images.githubusercontent.com/3083452/99973320-edf15c00-2d9f-11eb-8c67-4a82c935fbda.png">
<img width="908" alt="Screen Shot 2020-11-23 at 3 20 29 PM" src="https://user-images.githubusercontent.com/3083452/99973339-f21d7980-2d9f-11eb-8e65-9457e2b07926.png">
<img width="908" alt="Screen Shot 2020-11-23 at 3 22 51 PM" src="https://user-images.githubusercontent.com/3083452/99973342-f34ea680-2d9f-11eb-951e-56686957974e.png">

**Comment by nathangibson** [comment]
@MalindaT I think this is done and I just need to check it, right?

**Comment by nathangibson** [comment]
@hannafriedel Here are some of the guidelines/questions we've discussed regarding tagging.
