### ISSUE TITLE
Make URIs for works

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#38]
(maybe convert lists from IAU?)

**Comment by nathangibson** [comment]
@lunadine I've now added work URIs to all list items and merged these into the master branch here: https://github.com/usaybia/usaybia-data/tree/master/data/texts/tei. You can check these out for example for Ibn Ridwan's works starting here https://github.com/usaybia/usaybia-data/blob/master/data/texts/tei/lhom-ar-14.xml#L3665. 

My plan is to also export the list to a spreadsheet, where we can collect some of the information about the works. The tagging is quite preliminary. There are certainly many that are misidentified or not identified, and my thought is to identify these in the spreadsheet and then systematically remove any wrong tags from the TEI docs. 

List items are also used for lists of sayings, so I did not put a work URI on any items that started with وقال. But there will be other sayings that have been wrongly tagged.

Whenever you think it would be helpful, we can merge these into your branch, but there will be some "conflicts" to manually resolve.

**Comment by nathangibson** [comment]
Still need to extract and export these.

**Comment by lunadine** [comment]
perfect, thanks so much. I will integrate these in my html document! Was the note  above (4 days ago) some task for me or is it only a reminder of what you wanted to do?

**Comment by nathangibson** [comment]
Oh sorry the note was just a reminder that I need to produce a list of all the work URIs by extracting them from the marked-up text.

**Comment by lunadine** [comment]
Just one question: you mentioned, you were thinking about creating a spreadsheet, which we have not done yet, right?
I think it would be useful, maybe I can take this task over and we talk today about the best way to do this? (I guess X-Querries? Would be perfect if we could match a column with the English translation of the titles next to it, if doable)

**Comment by nathangibson** [comment]
Sounds good. Let’s discuss today.

**Comment by nathangibson** [comment]
See #61
