### ISSUE TITLE
Check Ibn Ridwan excerpt (person & place tagging)

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#41]

**Comment by lunadine** [comment]
If you happen to notice any systematic mistakes, do not spend a lot of time on correcting these since you are quite busy right now. Just let me know about them and I will send you another version without such mistakes.

**Comment by nathangibson** [comment]
@lunadine What is the status of this? Do I still need to check this?

**Comment by nathangibson** [comment]
@lunadine I mean: I know I didn't check it but I'm not sure if this is still helpful for you or if you're doing something else.

**Comment by lunadine** [comment]
I closed this since it is not relevant anymore and Malinda and me tagged Chapter 14; see issue #106
