### ISSUE TITLE
Correct Names, Entries, and Section numbers in LHOM Index

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#43]
@usaybia/mitarbeit This issue is now top priority for everyone. 

As part of getting some basic data ready to show in the upcoming workshop, we need to make sure we have clean names, entries, and section numbers for persons. 

Please take a look row-by-row at Columns E-I in the [Index Spreadsheet](https://docs.google.com/spreadsheets/d/1ujiT91ua3sA-WX86OWpuE-gDD_E-zONpI1dP70pXdWw/edit#gid=0) and check whether the right information is appearing in these columns (see below). Then please mark your initials in Column J. Each row only needs to be checked by one person, and only the rows with URIs need to be checked. 

You can overwrite the formulas and manually correct anything when it is obvious. When you have a question, right-click and add a "Comment" to the cell. 

If you look at column K you can sometimes tell what it was supposed to be.

Thanks!

Name | Entry  | Refs | Checked Name, Entry, Refs?
 -- | -- | -- | --
Should only contain names, not descriptions or dates. Correct manually as needed. | Should contain the name and description, but no section numbers or list of works. Correct manually as needed. | Should contain only section numbers. Lists of works are okay. Correct manually as needed. | Please mark your initials. Add a comment if you have a question. Only check items that have a URI.

**Comment by RobinSchmahl** [comment]
@nathangibson 

If in the Entry-Section it reads "author of work x", does that still count as a description or is it already a list of works?

Thanks!
R

**Comment by MalindaT** [comment]
If there is a questionmark, because it is uncertain if it was the name of the person or not, should it be still deleted in the "Name" Column? 

![image](https://user-images.githubusercontent.com/46726275/85225831-1c73a100-b3d4-11ea-90e4-b6456434e43f.png)

**Comment by nathangibson** [comment]
> @nathangibson
> 
> If in the Entry-Section it reads "author of work x", does that still count as a description or is it already a list of works?
> 
> Thanks!
> R

Yes, that is helpful as a description. But we don't need to include more than one work in the Entry column.
