### ISSUE TITLE
Tag places in chapter 12-13

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#52]
Please use recogito to tag places in ch. 13: https://recogito.pelagios.org/document/wcxswjvlr76umn

When a place is automatched, click "change" and match it with the following in order of priority:
D (Dare)
P (Pleiades)
K (Kima)
G (Geonames)

Also add the Usaybia.net URI for the place once we have place URIs (soon hopefully!)

**Comment by nathangibson** [comment]
Please add Usaybia.net URIs as tags to each tagged place. You can get them from [this Recogito doc](https://recogito.pelagios.org/document/gaasm4mbmx24qg) or [this Google sheet](https://docs.google.com/spreadsheets/d/1B6vJjZjUbCX-oyqmrgVmVq7GmyqvaAjfBlzcIYnwhpQ/edit#gid=0)

If you can't find a Usaybia.net URI for it, please tag it with the tag: no uri

All places in the Arabic text should have a URI or the tag "no uri". If you can't find a match for the place name in Arabic script, you can match the Latin-script place name in the Recogito places index document instead. 

Types of places we want to tag:
- cities, towns, villages
- named parts of cities, named gates
- places where people meet, including houses, mosques, churches, synagogues, markets, schools (madrasa)
- geographical regions (like Zagros Mountains)
- political regions of the time (like Iraq, Egypt)

Types of places we don't want to tag: 
- modern political regions, as are often found in Geonames (modern nation of Iraq, modern nation of Egypt)
- institutions that are not specific places people meet (like Bayt al-Ḥikma -- despite the name it is more a group of people than an actual place)

A further point: 
- When you're matching the place with another database, we prefer places with coordinates/locations, as long as it is accurate. But if the one with coordinates is not quite accurate (maybe a modern region instead of the ancient one), then it's better to do the accurate one without coordinates.

Clear? Questions?

**Comment by MalindaT** [comment]
Hey! I finished Chapter 13 on Recogito. 
There are a few things I am asking myself concerning:  

1. the city Cairo (al-Qahira) and al-Fustat. When he just talked about Cairo and not specifically as al-Fustat I used the other URI and "new" geodates. 

2. For ancient Iraq and Syria are no good geodates in the databases. Sometimes there are the roman names and places for the regions, but they look very different than the same named regions in the islamic times. What do you suggest? 

If you have time maybe you can watch through it and tell me what you think about everything :)

**Comment by nathangibson** [comment]
> Hey! I finished Chapter 13 on Recogito.

Wonderful! I should take a closer look at the matches but what I've seen so far is great.

> There are a few things I am asking myself concerning:
> 
>  1. the city Cairo (al-Qahira) and al-Fustat. When he just talked about Cairo and not specifically as al-Fustat I used the other URI and "new" geodates.

I think this is fine for now. We might think about refining it later.

>  2. For ancient Iraq and Syria are no good geodates in the databases. Sometimes there are the roman names and places for the regions, but they look very different than the same named regions in the islamic times. What do you suggest?

Yes, regions are tricky with geodata. I think we shouldn't match them to other databases unless we're really sure it's defined the same way. For political regions you probably won't find good matches normally. That's okay, the important thing is still to tag them with the Usaybia URI where one exists. You may have more success matching natural/non-political regions such as Jazira or Nile delta.

I'll be out of the office for a week, but until I get back can you continue with tagging places in ch. 12 here: https://recogito.pelagios.org/document/cr2ljemmn0sexk ? Thanks.

**Comment by nathangibson** [comment]
By the way, the formatting in ch. 12 doesn't look nice in Recogito but I hope you can still read it okay.

**Comment by MalindaT** [comment]
Is it important that the formatting looks nice? It is a bit hard to read, but not impossible.

**Comment by nathangibson** [comment]
No, the formatting doesn't matter. I'm just sorry it's hard to read. 

Great that you finished it! I guess it is quite a bit shorter than chapter 13. I'll try to get you something new tomorrow.

**Comment by nathangibson** [comment]
I'm creating a new task/issue for you but I'll close this one since you completed it!
