### ISSUE TITLE
Visualization - Cytoscape - general Questions

### ISSUE THREAD

**Issue by lunadine** [usaybia/usaybia-data#59]
There is no hurry in answering my questions here, I was just looking for a good place to put them as I assume that I will come up with further questions in future. 
I am trying to get more accustomed to cytoscape .
So, I created a sample file with people connected to Ibn Ridwan, Ibn Butlan and the Calif, very similar to the tsv. table "index-relations". It worked quite well so far, I was able to extract the required network, to adapt the layout and to display some tools for analyses such as betweenness centrality. But I face some problem in replacing the URI with the proper names.
My notes tell me, that I have to import the same file again, however as a table to a network collection (with person 2 URI as key, I import nothing from person one and add the data-file symbol to person 2) is this correct so far?
I am somehow not getting rid of the URIs

![cytoscape 1](https://user-images.githubusercontent.com/50455791/91078102-7007a280-e642-11ea-8103-c1ca222124a4.jpg)
![cytoscape 2](https://user-images.githubusercontent.com/50455791/91078106-739b2980-e642-11ea-865b-b337ed18dd9d.jpg)

**Comment by nathangibson** [comment]
@lunadine Sorry I forgot to discuss this with you today! 

There are potentially two issues here. 
 1. You have to get the Person 1 and Person 2 name or entry into the _same_ column, so when you do the second import as you're doing, you have to name the uri and entry/name columns to match the ones you used for Person 1. An alternative is to have your node information (uris & names) for persons in a separate sheet from your edge info (just uris and relations). The more recent version of this spreadsheet does that https://docs.google.com/spreadsheets/d/1rfuZR5i3JDve0MapTFVzcU79Arwg8ZbCiE-Y6sXTa2c/edit#gid=0 . Then you do 2 imports, first the node table, then the edge table. 
 2. Also, in the Style > Node tab in Cytoscape you have to set the "Label" to your custom name column (whatever it's called) and select "passthrough mapping." 

Hope this helps. Let me know if it works.

**Comment by nathangibson** [comment]
Unless you have more questions on this, I'll archive it :-)
