### ISSUE TITLE
Create Bibliography Entries from LHOM

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#62]
@vanessa612 Please use this spreadsheet https://docs.google.com/spreadsheets/d/1d7Rlnsteja2sd4911DOAyCrRZWmeZG27NtBDwgH8e0U/edit#gid=0 to find items and add them to our Zotero library. 

One (or sometimes more) persons or places treated by the item should be added as Zotero tags in the format 
`Person: Short Name {URI}`
and
`Place: Name {URI}`

Please also add the tag `Source: LHOM` to all of them.

For example, the first row "Abattouy, Greek mechanics in Arabic context" takes you to [this Worldcat item](https://www.worldcat.org/title/greek-mechanics-in-arabic-context-thabit-ibn-qurra-al-isfizari-and-the-arabic-traditions-of-aristotelian-and-euclidean-mechanics/oclc/50460739&referer=brief_results) you can save in Zotero. Then the tag `Person: Thābit ibn Qurrah {https://usaybia.net/person/2196}` should be added. (It looks like we don't have a URI for al-Isfizari so you can skip that.) 

Please refer to our [Zotero guidelines](https://www.zotero.org/groups/2349036/usaybia.net/collections/PFJ94VKC/items/BJZE7IUB/collection) for adding items. You can ask questions in this issue.

When you find multiple matching items, use the one that seems to have the most accurate details. If the book is originally Arabic, we should import the Arabic script title/info when it is available.

Thanks!

**Comment by nathangibson** [comment]
Forgot to mention: You can find the URIs simply by searching the Usaybia.net website

**Comment by nathangibson** [comment]
@FlavioZeska How's it going with the bibliography?

**Comment by FlavioZeska** [comment]
@nathangibson Generally speaking it takes longer than expected, but I want it to be done properly. I´ll be glad , if you check a few entries in Zotero as samples.
I have encountered some difficulties with #315 (Worldcat is just offering me scattered pieces of an article) #316 (is a revised reprint of the original PhD thesis; should I leave it as a PhD entry nevertheless?) and #318 (I am not sure how to enter this database into Zotero) and #322 (I have entered it manually as an article, although it only exists as the whole book in Worldcat). Until when do you expect the LHOM task to be finished? Thank you

**Comment by nathangibson** [comment]
@FlavioZeska Sure, I'm happy to check some. Since this is a new process for us, I wasn't sure how long to expect it to take. But we can try to figure out ways to make it more efficient. So, to help with that:
1. What's taking a long time? Is it that the links in the spreadsheet don't help you find the item quickly? Or that it takes a long time to edit in Zotero? 
2. Right now the list is sorted by author but we could try to sort it differently. One way would be to first go through and identify the relevant persons/places in the list with Usaybia URIs, then enter all of the related ones together. Do you think that will help?

**Comment by nathangibson** [comment]
@FlavioZeska I'm checking number 322 as an example, Daiber, ‘Survey of Theophrastean material’ = Hans Daiber, ‘A survey of Theophrastean material indirectly transmitted in Arabic’, in Fortenbaugh, Huby &amp; Long, **Theophrastus**, 103–114.

(https://www.worldcat.org/title/theophrastus-of-eresus-on-his-life-and-work/oclc/812948485 in WorldCat)

- This is actually a chapter in a book, so the "type" should be "Book section" and it should include the place & publisher. You'll get used to seeing the way books look in WorldCat vs. journals (but WorldCat typically has books, not individual journal volumes). 
- The person tags should be in the format `Person: Theophrastus of Eresos {https://usaybia.net/person/2219}`
  -  Note the curly braces `{ }`
  - Also note that the URI is without the `/tei` portion on the end. (I think you're using the clipboard button in the search results, which gives you tei on the end.) But these tags are easy to change all at once in the left sidebar of Zotero if you expand the tags (sometimes hidden at the bottom), then right-click on a tag and "Rename". 
- For all the items you add, please also add a tag `Entered: ` with your screen name so that we can properly credit the entry.

Make sense? Questions?

**Comment by FlavioZeska** [comment]
@nathangibson Thank you for your review. I have now included your remarks into zotero. 
Entering an item is taking me up to seven minutes. - I wasn`t sure if I was too slow. The list itself is at its current state efficiently organized.
The only question remaining so far is concerning the "Usaybia" tag. Which URI should I enter?

Thank you in advance

**Comment by nathangibson** [comment]
@FlavioZeska It's not surprising that it takes that long, but then I need to think about what we should do. With almost 2,000 items that would take all your time. So maybe we'll need to find a way of selecting only some or converting them automatically ... In the meantime, please keep going and we can discuss at the next meeting. 

I assume you are using the Zotero Connector to import the item from Worldcat or other sites (instead of entering it manually)? Which part takes the longest, finding the correct item on the web or correcting/adding information to it once you import it? 

What do you mean by the Usaybia tag, where did you see it? If you mean the tag for Ibn Abi Usaybia himself, it's `Person: Ibn Abī Uṣaybiʿa {https://usaybia.net/person/926}`

**Comment by FlavioZeska** [comment]
@nathangibson Thank you for your quick response. 
Yes, I am using the Connector tool, but most time is consumed by comparing entries with the corresponding Worldcat items. Sometimes they do not match and therefore I have to undertake a little search on the web, in order to enter for example the full title of a bookchapter etc. Sometimes the corrsponding Google scholar or Google book links are too vague or misleading. Nonetheless it is an interesting - to some extent - fun task, because with almost every entry I get to know a different subcategory of the project.

**Comment by nathangibson** [comment]
OK, @FlavioZeska, thanks for the details. Let's try some things to speed this up:
1. I changed the search formula for the links a bit, since I noticed that has problems when the authors have an `&` sign, which is pretty common. This should give you more accurate search results for some.
2. I also added (in columns J+) some columns that split the items into parts. It is irregular, but it makes different parts easy to copy for searching. If you hold down CTRL (or CMD on Mac) and then click on the cells you want to search for (even if they're not right next to each other, you can press CTRL-C to copy them, and CTRL-V in the search on WorldCat or Google Scholar. I usually find that a combination of the author's name, part of the title, and the date is usually enough. (See screenshot.)
3. For now, please skip Arabic authors or items with transliterated Arabic titles. These are probably time consuming because the transliteration can vary quite a bit. We'll figure out a different strategy for these. 
4. Don't search around a lot. If the information seems inaccurate or incomplete in WorldCat/Google, then you can copy it from the spreadsheet or mark it. Otherwise you can mark it "not found" in column G if you don't find it easily. 
5. When you find examples of things that take a lot of time to find, please put them here so I can figure out how to improve the system. 
Thanks!

**Comment by FlavioZeska** [comment]
@nathangibson Thank you for your response. It does improve the process a lot. 
Besides I have a question related to the taging process. In #335 for example the Worldcat entry is offering me the name ar-Razi in the title, which I already have taged. The short table of content however is displaying more names like Ibn Sina (https://www.worldcat.org/title/traite-sur-le-calcul-dans-les-reins-et-dans-la-vessie/oclc/14806460&referer=brief_results). In the past I have taged all names available in the e.g. abstracts, but have now come to the conclusion it might be in some cases too much. So therefore I am asking you, if I have to tag all names displayed in the worldcat entry or just those appearing in the headlines.

Thank you

**Comment by nathangibson** [comment]
@FlavioZeska Glad it helps. 

1. Regarding how many names to tag, I think only those apparent from the title, for the sake of time. 
2. Regarding translations and editions, yes, the guidelines are probably not clear ... Please 
   1. Put the ancient author _only_ as a tag, such as `Author: Abū Bakr al-Rāzī {https://usaybia.net/person/787}`. Do not add a `Person: ` tag for the same person, and do not include the person in Zotero's Author field. The reason is that we need to identify the ancient author by URI, which we can only do well in the tags.
   2. Put the modern translator/editor as an author in Zotero's Author field. 
   3. Add the tags `Type: Translation` and/or `Type: Edition`. (Sorry, this is new, but necessary.) So 335 for example would be both since WorldCat says "Text and French translation on opposite pages". 
   4. Please make sure to include the language codes in the Language field, e.g. for 335 it is `ar, fr`

**Comment by FlavioZeska** [comment]
@nathangibson Thank you for the update. I am reworking the entries now. 
Sorry for bothering you again, but while revisting the entries in Zotero, another question came into my mind.
For the sake of standardization: How many names of a person should I add to a tag in Zotero? The initial person: tag Thābit ibn Qurrah of this thread could be expanded by al-Ḥarrānī acording to our website entry. In some cases, like al-Razi or Ibn Sina, the short version might already be long enough. But of course this are non objective criteria and therefore not standardized.

**Comment by FlavioZeska** [comment]
@nathangibson Here is another question, this time concerning an actual name in the Usaybia database: About LHOM item #314: Here I was confronted with a certain Ibn Athradi in connection to Ibn Butlans banquet of the physicians, the only entries I was able to find in our database were however about a few persons named Ibn Uthrudi (https://usaybia.net/search.html?keyword=Ibn+Uthrud%C4%AB). After working time I undertook a little search on my own and was able to find the name Ibn Atharudi (e.g. https://books.google.de/books?id=i8sUAAAAIAAJ&pg=PA12&lpg=PA12&dq=ibn+ithirdi&source=bl&ots=Pxz2U0sZvT&sig=ACfU3U1Bp0F3tVgDLWUvVHs1lpG6MNevyw&hl=de&sa=X&ved=2ahUKEwjPo-jOgsLuAhUwx4UKHd8_BUQQ6AEwA3oECAkQAQ#v=onepage&q=ibn%20ithirdi&f=false). So I wanted to ask what to do.
Thank you in advance

**Comment by nathangibson** [comment]
@FlavioZeska Summary of our conversation today:
- Please add the Zotero link or item number to the spreadsheet when you enter a new item. You can get this by just keeping this page open https://www.zotero.org/groups/2349036/usaybia.net/library , sorted by "Date Modified". (Click on an item and copy the address from the address bar.) If this is taking a long time, you could try the alternative of pasting the "abbreviation" from the spreadsheet into the "Short Title" field in Zotero. 
- If you find multiple items in Worldcat (or elsewhere), choose any of them with the correct date and title. If the date isn't the same, try to get the same edition, but reprints are okay. 
- If there is no Usaybia.net entry for a person you need to tag, still add the tag `Person: ` with the name. We will add a URI later. 
- It is important to have something in the language field. But if full names are used like "English" instead of "en" you can leave it for us to correct en masse later.

**Comment by FlavioZeska** [comment]
@nathangibson Lately I have encountered another difficulty. Sometimes I am unsure when to add the Type: Edition tag since our Zotero guidelines are in progress concerning this tag and sometimes Worlcat entries are not always clear. So in order to assure myself, I wanted to ask you: What exactly is our definition of the Type: Edition tag ?
Thank you

**Comment by nathangibson** [comment]
@FlavioZeska Yes, sorry for the lack of clarity! `Type: Edition` should be used when the bibliography item contains a historical text in the original language, e.g., an Arabic text. It can be used together with `Type: Translation` if there is _also_ a translation of the text into another language. If it is only a translation and does not include the original text, please use only `Type: Translation`. 

These things are often not clear from the Worldcat entry. Sometimes it might not be clear if it's only a study of the text or also an edition/translation. So you only need to tag edition/translation if you see it easily from the Worldcat item.

**Comment by FlavioZeska** [comment]
@nathangibson I am a bit unsure how to enter multivolume works like e.g. encyclopaedias. Into which field in Zotero do I enter the number of volumes? Thank you

**Comment by nathangibson** [comment]
@FlavioZeska There is a "# of volumes" field in Zotero. Please note that we enter encyclopedias with the item type "book".

**Comment by FlavioZeska** [comment]
@nathangibson if you want, you are invited to check a few random samples of our bibliography and comment since we have now over 300 entries and counting. Thank you in advance

**Comment by nathangibson** [comment]
Hi @FlavioZeska , Here is some feedback after checking a few items:

Overall, this is looking really great. Consistently accurate, high quality. Great work. 

I've added "child notes" to a few items in Zotero with some things to correct. I'll paste them here too. Once you've changed these (if I haven't already), you can delete the note item in Zotero. 

1. The main thing is to correct something I told you wrong at one point (sorry!). For modern editors of an ancient work, please enter them as "Editor", not "Author." This applies to everything tagged "Edition." Currently some of these are listed as "author" and some as "editor." I'm sorry I told you this wrong earlier. It shouldn't take too long to switch back: You can go through the smart folder I've created in Zotero "Change author > editor" and just switch all of them. 
2. Please enter encyclopedia articles as "Book Section". (E.g., Jacquart, Danielle. “Ibn Māsawayh, Yūḥannā.” In Encyclopaedia of the History of Science, Technology, and Medicine in Non-Western Cultures, edited by Helaine Selin, 424–25. Dordrecht; Boston: Kluwer Academic, 1997.)
3. For Arabic names in the editors, if you're not sure which name should be used as the surname (as in this case perhaps), you can click the button to the right of the name "switch to single field." This will put the entire name of the author in one field, not split by first/last name. (E.g. الجازي, الراضي, and فاروق عمر العسلي, eds. كتاب طب الفقراء والمساكين. تونس: المجمع التونسي للعلوم واالآداب والفنون, 2009.)
4. Please pay careful attention to diacritics such as "ā" vs. "a" and ʿ or ʾ vs. '. Worldcat sometimes has these wrong, so it is best to check against the LHOM list. (E.g. Bos, Gerrit. Ibn al-Jazzār on sexual diseases and their treatment: a critical edition of Zād al-musāfir wa-qūt al-ḥāḍir, Provisions for the traveller and the nourishment for the sedentary, Book 6. Sir Henry Wellcome Asian series. London: Kegan Paul International, 1997. and Rabin, C. “Ibn Jamīʿ on the Skeleton.” In Science, Medicine, and History : Essays on the Evolution of Scientific Thought and Medical Practice Written in Honour of Charles Singer, edited by Edgar A Underwood, 1:177–202. London: Oxford University Press, 1953.)
5. If LHOM cites a specific edition, please enter this in the "Edition" field. (E.g. Wright, William, and M. J. de Goeje. The travels of Ibn Jubayr ed. from a ms. in the university library of Leyden. 2nd revised. New York: AMS Press, 1973.)
6. Sometimes LHOM gives reprint information. It is not important enough for us to enter the reprint as a separate item in Zotero, but you can just paste the reprint info from the LHOM list into the "Extra" field in Zotero. E.g. When you have reprint information, you can just copy this into the "Extra" field like: Repr. of **Les générations de médecins et des sages**, ed. Fuʾād Sayyid (Publications de l’ Institut d’ Auteurs Orientaux, 10). Cairo: Imprimerie de l’ Institut Français d’ Archéologie Orientale, 1955. 
7. When there are multiple languages, please enter them with commas instead of "and". E.g., "Arabic, Spanish". But ultimately we want to use the 2- or 3-letter abbreviations from https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes such as "ar, es". See the guidelines "14. Language and Script." Don't worry about correcting the ones you've already done. We can correct these en masse later.

**Comment by FlavioZeska** [comment]
@nathangibson Thank you very much for your revision and constructive criticism! 

1) I have now switched all authors to editors, at least where possible. The "dissertation" type entry however does not allow switches to "editor" and in the case of some book chapters, where editors of texts do not equal editors of the whole modern book entry, I find it confusing (e.g. Meyerhof, Max, Las operaciones de catarata de ʻAmmār ibn ʻAli al-Mausilī). 
2) Encyclopaedia entries are now corrected.
3) Thank you for this advice; sometimes Worldcat clarifies it by commas, sometimes not, so it helps me.
6) Should the reprint information be placed above or below the OCLC number or does it make no difference?
7) For clarification: What is the ISO 639-1 code for Syriac? Because I have only encountered the ISO 639-2 code (syc).

Thank you in advance

**Comment by nathangibson** [comment]
@FlavioZeska 
1. I'll try to take a closer look at this.
2. Great.
3. Good.
4. Below.
5. Please use "syr" for Syriac. (There are some complicated issues around this.) ISO 639-2 (or 3 or 4 or 5) codes are fine when an ISO 639-1 code doesn't exist.

**Comment by FlavioZeska** [comment]
@nathangibson 
1. Does this also apply to modern translators, i.e. should they be switched to "translators" in zotero? 

Thank you

**Comment by nathangibson** [comment]
@FlavioZeska 
1. In the case of editions which are dissertations or book chapters, yes, we should leave the modern editor as "author". But please use "editor" instead of "translator." Unfortunately Zotero doesn't export translators correctly. So it is better if we leave them as editors and we'll know from the "Type: Translation" tag that they are translators.

**Comment by nathangibson** [comment]
1. Duplicates -- entries that are in LHOM 2x, once for ancient author, once for modern editor --> please simply add the Zotero ID to the duplicate row in the table.
2. Manual Entry in Zotero for items you can't find in online databases
3. New persons -- we'll meet to discuss

**Comment by FlavioZeska** [comment]
@nathangibson 

Here the mentioned list of entries, which came to my attention.

Typos

#1257 Isḥāq ibn ʿAlī al-Ruhāwī, Identity section adab (?) instead of acab https://usaybia.net/person/1257 
#1306 al-Jāḥiẓ, Identity section  adab (?) instead of acab https://usaybia.net/person/1306 

#1384 al-Khālidiyyān one zero short, second death year, miladi 390/100[0] https://usaybia.net/person/1384
#1586 Muʾayyid al-Dīn al-ʿUrḍī (ca. 596; closing bracket missing, besides, birth date in heading? https://usaybia.net/person/1586
#2168 al-Ṭabarī, Identity section, space missing (JarīrṬabarī) https://usaybia.net/person/2168


Inconsistency

#1026 Ibn Khaldūn year of death Identity section (1406) vs Names section (1057) https://usaybia.net/person/1026


Other

#483 ʿAlī ibn Yaḥyā, names section: possible remains of work instruction? (` to`ease check punctuation) https://usaybia.net/person/483
#633 Bar Bahlūl, "ERROR" in occupation section https://usaybia.net/person/633
#713 Diocles, adding Diocles [of Carystus] for better differentiation? https://usaybia.net/person/713
#2432 Quṭb al-Dīn al-Shīrāzī (d. 710/1311), dates in heading? https://usaybia.net/person/2432
which date alignment? h/m-h/m (https://usaybia.net/person/1139) or h-h/m-m (https://usaybia.net/person/32)

Same Persons?

#61 and #2312 [Zotero entries all #2312] al-Yaʿqūbī, unique names Wāḍiḥ/Yaʿqūbī (https://www.britannica.com/biography/al-Yaqubi), https://usaybia.net/person/61, https://usaybia.net/person/2312
#136 and #1725 [no Zotero entries] Nāfiʿ ibn al-Ḥārith ibn Kaladah, Abū Bakrah ibn al-Ḥārith ibn Kaladah "son of the slave-girl Sumayyah and, probably, the physician al-Ḥārith ibn Kaladah" https://usaybia.net/person/136, https://usaybia.net/person/1725
#161 and #1136 [Zotero entries all #161] Ibn al-Ṭayyib "Abū l-Faraj ʿAbd Allāh", https://usaybia.net/person/161, https://usaybia.net/person/1136 
#598 and #1463 [Zotero entries all #1463] al-Malik al-ʿAzīz/al-ʿAzīz, same time of regency, miladi https://usaybia.net/person/598, https://usaybia.net/person/1463
#1229 and #1294 al-Irbilī, [no Zotero entries] same dates, https://usaybia.net/person/1229, https://usaybia.net/person/1294
#2201 and #2213 [Zotero entries all #2201] Theodosius https://usaybia.net/person/2201, https://usaybia.net/person/2213

**Comment by nathangibson** [comment]
@FlavioZeska Excellent, thank you for this!!

**Comment by nathangibson** [comment]
Reformatting ...

## Typos

- [ ] https://usaybia.net/person/1257 Isḥāq ibn ʿAlī al-Ruhāwī, Identity section adab (?) instead of acab https://usaybia.net/person/1257 
- [ ] https://usaybia.net/person/1306 al-Jāḥiẓ, Identity section  adab (?) instead of acab https://usaybia.net/person/1306 

- [ ] https://usaybia.net/person/1384 al-Khālidiyyān one zero short, second death year, miladi 390/100[0] https://usaybia.net/person/1384
- [ ] https://usaybia.net/person/1586 Muʾayyid al-Dīn al-ʿUrḍī (ca. 596; closing bracket missing, besides, birth date in heading? https://usaybia.net/person/1586
- [ ] https://usaybia.net/person/2168 al-Ṭabarī, Identity section, space missing (JarīrṬabarī) https://usaybia.net/person/2168


## Inconsistency

- [ ] https://usaybia.net/person/1026 Ibn Khaldūn year of death Identity section (1406) vs Names section (1057) https://usaybia.net/person/1026


## Other

- [ ] https://usaybia.net/person/483 ʿAlī ibn Yaḥyā, names section: possible remains of work instruction? (` to`ease check punctuation) https://usaybia.net/person/483
- [ ] https://usaybia.net/person/633 Bar Bahlūl, "ERROR" in occupation section https://usaybia.net/person/633
- [ ] https://usaybia.net/person/713 Diocles, adding Diocles [of Carystus] for better differentiation? https://usaybia.net/person/713
- [ ] https://usaybia.net/person/2432 Quṭb al-Dīn al-Shīrāzī (d. 710/1311), dates in heading? https://usaybia.net/person/2432
- [ ] which date alignment? h/m-h/m (https://usaybia.net/person/1139) or h-h/m-m (https://usaybia.net/person/32)

## Same Persons?

- [ ] https://usaybia.net/person/61 and https://usaybia.net/person/2312 [Zotero entries all https://usaybia.net/person/2312] al-Yaʿqūbī, unique names Wāḍiḥ/Yaʿqūbī (https://www.britannica.com/biography/al-Yaqubi), https://usaybia.net/person/61, https://usaybia.net/person/2312
- [ ] https://usaybia.net/person/136 and https://usaybia.net/person/1725 [no Zotero entries] Nāfiʿ ibn al-Ḥārith ibn Kaladah, Abū Bakrah ibn al-Ḥārith ibn Kaladah "son of the slave-girl Sumayyah and, probably, the physician al-Ḥārith ibn Kaladah" https://usaybia.net/person/136, https://usaybia.net/person/1725
- [ ] https://usaybia.net/person/161 and https://usaybia.net/person/1136 [Zotero entries all https://usaybia.net/person/161] Ibn al-Ṭayyib "Abū l-Faraj ʿAbd Allāh", https://usaybia.net/person/161, https://usaybia.net/person/1136 
- [ ] https://usaybia.net/person/598 and https://usaybia.net/person/1463 [Zotero entries all https://usaybia.net/person/1463] al-Malik al-ʿAzīz/al-ʿAzīz, same time of regency, miladi https://usaybia.net/person/598, https://usaybia.net/person/1463
- [ ] https://usaybia.net/person/1229 and https://usaybia.net/person/1294 al-Irbilī, [no Zotero entries] same dates, https://usaybia.net/person/1229, https://usaybia.net/person/1294
- [ ] https://usaybia.net/person/2201 and #https://usaybia.net/person/2213 [Zotero entries all https://usaybia.net/person/2201] Theodosius https://usaybia.net/person/2201, https://usaybia.net/person/2213
