### ISSUE TITLE
Check/discuss the current factoids for Ibn Butlan/Ibn Ridwan/ Ibn al-Khammar/Ibn al-Tayyib

### ISSUE THREAD

**Issue by lunadine** [usaybia/usaybia-data#64]
I am just creating this issue to keep in mind that 

 I need to update:
-  the <ab> <div> element 
- the work URI's
- general check 

and that we might want to talk about these some time

**Comment by nathangibson** [comment]
@lunadine Please update your branch :-)

**Comment by nathangibson** [comment]
@lunadine Now I see a commit from 25 days ago. Is that the latest version?

**Comment by lunadine** [comment]
Hello @nathangibson! I noticed the problem, I saved the files in my branch in the folder TEI and not in factoids (which was probably wrong?) in any way both 14-25 and 10-38 should be from 18.12 dec version and I added a "to be discussed" after 10-38. Sorry for the confusion!

**Comment by nathangibson** [comment]
@lunadine OK, I'll take a look!

**Comment by nathangibson** [comment]
@lunadine please note:
- listRelation needs a *start* and end tag
- relation needs a `@type` attribute (usually person)
- the `relation/@ref` should be a full URI to a Syriaca keyword (this is somewhat new). All snap relations are included in the Syriaca taxonomy
- the description should go inside a `desc` element inside relation
- names inside the desc should be marked with `persName` and `@ref` pointing to a URI so they can be linked

**Comment by nathangibson** [comment]
@lunadine Whenever a keyword doesn't yet exist in the Syriaca taxonomy we should add it in the list and notify @dlschwartz via the Google Doc. (See my commit just now.)

**Comment by nathangibson** [comment]
@lunadine Continuing the notes ... I  hope this isn't annoying ...
- The `citedRange` part number should correspond to the third number in the decimal, according to the LHOM numbering. E.g., this means 10.38.2
https://github.com/usaybia/usaybia-data/blob/2bc4c94a719e1d34f02cba6b5a53f27ebb8ce911/data/factoids/tei/lhom-10-38-to%20discuss.xml#L183

**Comment by lunadine** [comment]
@nathangibson many thanks for taking a look at it! I am sorry there are so many mistakes/problems in the file!

**Comment by nathangibson** [comment]
@lunadine 
- The description of the factoids should be rephrased in the 3rd person, using names, so that it can also be read out of context. E.g. https://github.com/usaybia/usaybia-data/blob/1ab5a5c51ab0509500ad76076bb29fd8d917fb83/data/factoids/tei/lhom-10-38-to%20discuss.xml#L193

**Comment by nathangibson** [comment]
> @nathangibson many thanks for taking a look at it! I am sorry there are so many mistakes/problems in the file!

No worries, I'm being picky so that we can work toward consistency :-)

**Comment by nathangibson** [comment]
@lunadine 
- events can't take the relation attributes ref, active, passive. But if the event establishes a relationship we can put a listRelation/relation at the end of the desc.
- the reg and orig dates have to be inside a `choice` element to show that they are alternatives (one is the "regularized" text, the other the "original") 
- An uncertain date uses `@notBefore` and `@notAfter` instead of `@when`
- I think spear is using # plus camelCase for the `@datingMethod`

**Comment by nathangibson** [comment]
@lunadine I'll close this issue but you can reopen it if there's more to discuss
