### ISSUE TITLE
Set up accounts for web services (@hannafriedel)

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#70]
- [x] Github
- [x] Slack
- [x] [Google Docs](https://drive.google.com)
- [x] [Zotero](https://zotero.org)

**Comment by nathangibson** [comment]
@hannafriedel Welcome to Github! You can close this issue when you're finished with these :-) I sent you a Zotero invitation

**Comment by hannafriedel** [comment]
Thanks :) Zotero is new for me, but not completely, I've used EndNote before.
