### ISSUE TITLE
Do Github actions tutorials

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#75]
Please do courses 1–3 at https://lab.github.com/githubtraining/devops-with-github-actions

If you're interested you can continue with courses 5–7 after that.

**Comment by hannafriedel** [comment]
I completed courses 1-3, though it took me ages to get the Docker up and running. I will do 5-7 as well, but am excited to start my first "real" assignment after that

**Comment by nathangibson** [comment]
Sounds good! Docker can be complex but it is amazingly powerful. Did you get it up and running on your own machine? 

Courses 5-7 involve more specific technologies like Docker and JavaScript. Don't be intimidated, the instructions should be enough to copy and paste and get you through them even without knowing how to code them from scratch.

**Comment by hannafriedel** [comment]
I got Docker to work, it took some changes in my BIOS and other stuff, but their help pages are amazing.

**Comment by nathangibson** [comment]
Cool! But BIOS changes ... that's intense. 

Something you can try if you're interested:
The docker package I made before from the usaybia-data repo is only the data files (XML). Just now I got a workflow working for the srophe-exist-app repo, which has the full web application. In docker you can pull it with `docker pull ghcr.io/usaybia/usaybia-srophe-exist-app:latest`. Then you can do `docker run -it -d -p 8080:8080 -p 8443:8443 --name usaybia-srophe-exist-app ghcr.io/usaybia/usaybia-srophe-exist-app:latest`. After 1-2 minutes you should be able to go to localhost:8080 in your web browser and see exist running. If you click on Usaybia.net you'll see the website running on your local computer. (Some things you click on won't work locally because it'll try to send you to e.g. http://localhost:8080/persons/browse.html instead of http://localhost:8080/exist/apps/usaybia/persons/browse.html , but you can change the address in the address bar to add exist/apps/usaybia/.

**Comment by nathangibson** [comment]
Before you can pull you have to login with docker to ghcr.io, which is a bit complicated. The best is using a personal access token with read:packages permissions which you can create here: https://github.com/settings/tokens/new?scopes=read:packages , then copy the code into a text file (e.g. your_token_file.txt). 

Then you can login like this (unix commands, I'm not sure about Windows): 

`sudo cat ~/your_token_file.txt | sudo docker login ghcr.io --username hannafriedel --password-stdin`

Sorry this is rather complicated. If you like you can just wait to try it out until I make the docker image public, then you won't have to log in.

**Comment by hannafriedel** [comment]
Regarding your last comment, that's why I made the BIOS changes. now I can directly login with Docker via GitBash, because I run a virtual Linux machine on my windows system, so everything works smoothly.

**Comment by nathangibson** [comment]
Oh, very interesting! I've never tried GitBash.

**Comment by hannafriedel** [comment]
It was recommended in the tutorial and can be integrated with Visual Studio Code so I thought it would be a good option for me

**Comment by hannafriedel** [comment]
I got stuck on the fifth tutorial because the tutorial didn't agree with me.
Maybe you could assign me the issues you want me to do, and I will learn on the go, GitHub has incredible help forums so I will find my way around.

**Comment by nathangibson** [comment]
OK, I'll create another issue and you can close this one if you're ready.
