### ISSUE TITLE
Create workflow to test version number from expath-pkg.xml

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#82]
More details in a moment ...

**Comment by nathangibson** [comment]
@hannafriedel 

In our release workflow, we want to check whether the version number in the file /expath-pkg.xml is correct.
https://github.com/usaybia/usaybia-data/blob/a57e05a72fc0615e5e5b4ba9caf398c748db0ba0/expath-pkg.xml#L2

You can start by using this workflow file I've set up https://github.com/usaybia/usaybia-data/blob/issue-82-test-version/.github/workflows/test-version.yml to just get the version number and output it. 

XML isn't that easy to work with in the shell or javascript, so you can try using the YAML/JSON/XML Converter action to convert the XML to JSON and then get it using JSON. 

See https://github.com/marketplace/actions/yaml-json-xml-converter-action for inputs and examples

Once this is working, let me know, and we'll integrate it into our release workflow to test that the version number is correct when the release is triggered.

Any questions? This might turn out complicated, so don't worry if you run into problems, just ask.

**Comment by nathangibson** [comment]
PS The basic idea with JSON is that you can treat it like a javascript object using dot notation. E.g. `package.version`

If you need a JSON tutorial, see https://www.w3schools.com/js/js_json_intro.asp

**Comment by hannafriedel** [comment]
Hi Nathan, converting the data was easy enough and I can print the whole thing to the console but I do not understand how I can access a single object value.

**Comment by nathangibson** [comment]
Congrats on getting the data object. Hmm, you're right, to get the value out of the object array you'll need to use javascript to process it. Try something like 
```
      - name: Get version number
        id: get-version-number
        uses: actions/github-script@v3        
        with:
          script: |            
            var str = "${{ steps.xml2json.outputs.data }}";
            return str.package.version; # You might need to adapt this depending on how the data object is structured
          result-encoding: string
```
Similar to what I've done at https://github.com/usaybia/usaybia-data/blob/486c2a58fd02ef041eba108979372720afeb71ef/.github/workflows/release-dev.yml#L50

Hope that helps!

**Comment by nathangibson** [comment]
Oh, and then you'll need to print the output of the get-version-number step
