### ISSUE TITLE
Install VSC Emmet Snippets

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#84]
I've found something that will make our coding more efficient! You'll be able to tag Arabic names more easily and create factoids more easily.

1. In Github, do Fetch origin (and Pull if needed) on the development branch to make sure you're up to date. (@MalindaT and @lunadine I've updated your branches so it'll work there too.)
2. In VS Code, go to File > Open Workspace and select the usaybia-data.code-workspace file in the usaybia-data folder.
3. In VS Code, try selecting some text in an XML document and pressing CMD-Alt-E (Mac) or CTRL-Alt-E (Windows) to "wrap your selected text with an abbreviation." (You can also get to this by pressing CMD-Alt-P (Mac) or CTRL-Alt-P (Windows) to open the command toolbar and then typing "Wrap" > click on "Emmet: Wrap with abbreviation".)
4. In the Abbreviation toolbar that opens, type `prnm` and enter. You should get the text you selected wrapped with `<persName ref="">...</persName>`. @lunadine You can also type the abbreviation `factrm` for a mutual relation factoid.

Does it work? If not, we can go through it on Monday. 

Check beside your name when you've done this. The last person to do it can close the issue. 
- [x] @lunadine 
- [x] @MalindaT 
- [x] @hannafriedel 
- [ ] @FlavioZeska 

___
Edited: Updated the instructions and codes.

**Comment by nathangibson** [comment]
Edited: I forgot step 2 earlier! Sorry!

**Comment by lunadine** [comment]
Hello Nathan,
many thanks, this sounds really useful! Unfortunately, it does not work for me, yet.  Is it correct that usaybia-data.code will be in a separate tab in VS Code and then I go back to my XML doc? I receive the normal brackets around the selected text section just with <pn> abc </pn> and the same with relm, I can also show you tomorrow.

**Comment by nathangibson** [comment]
@lunadine Maybe try this: close all documents in VSC. Then quit VSC completely. Reopen VSC. Then go to File > Open Workspace and select `usaybia-data.code-workspace`. Then open your XML doc you want to edit (but it must be somewhere inside the usaybia-data repo).

**Comment by nathangibson** [comment]
Also it's a relatively new feature of VS Code, so you might need to update VSC.

**Comment by nathangibson** [comment]
I've moved the workspace settings so that the workspace is automatically opened when you open the usaybia-data folder in VS Code. So the snippets should automatically install if you've updated from Github.

**Comment by nathangibson** [comment]
@MalindaT I think I figured out the problem why the new snippets weren't working for you. Just after I updated the files on your branch on Monday, the two files were deleted again before you synchronized. Maybe it was your Microsoft OneDrive trying to synchronize that did that. So when you committed and pushed in Github, it deleted the files on your branch (in the folder named `.emmet`). 

The solution is: 
1. Do "Fetch origin" and then "Pull" to get the latest changes again with the updated files. 
2. Close VS Code and reopen it. Go to File > Open and choose the usaybia-data folder. 
3. If you again see changes in Github to files in the `.emmet` or `.vscode` folders, don't commit them. You can uncheck the box beside them before pressing commit. 

Let me know if it works now! E.g., the snippet `prnm`.
