### ISSUE TITLE
Add version test to release workflows

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#87]
@hannafriedel Time to implement the workflow you wrote! Continuing in the branch issue-82-test-version let's add the logic from the test workflow you created (https://github.com/usaybia/usaybia-data/blob/issue-82-test-version/.github/workflows/test-version.yml, #82) to the release workflows (starting with https://github.com/usaybia/usaybia-data/blob/issue-82-test-version/.github/workflows/release-dev.yml) .

- [x] Before https://github.com/usaybia/usaybia-data/blob/396871cef3c49f17ff6ddcb006899fc88e0c59be/.github/workflows/release-dev.yml#L59 in the update_release_draft job, copy the get-version-number step from the https://github.com/usaybia/usaybia-data/blob/issue-82-test-version/.github/workflows/test-version.yml file. 
- [x] Add a step after that that gives an error message if the version number is not correct. See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif for the syntax. I think it will be something like `if: ${{ steps.get-version-number.outputs.result != steps.set-version-variables.outputs.result  }}` and then `run: echo "Please change the version number in expath-pkg.xml to ${{ steps.get-version-number.outputs.result }}"`
- [x] Add a conditional to the step [upload-release-asset](https://github.com/usaybia/usaybia-data/blob/396871cef3c49f17ff6ddcb006899fc88e0c59be/.github/workflows/release-dev.yml#L64), something like `if: ${{ steps.get-version-number.outputs.result == steps.set-version-variables.outputs.result  }}`
- [x] add `- issue-82-test-version` as a new line at https://github.com/usaybia/usaybia-data/blob/396871cef3c49f17ff6ddcb006899fc88e0c59be/.github/workflows/release-dev.yml#L9. This will help you test by automatically triggering the workflow. Note: The upload-release-asset step **will** fail if there's [a release draft](https://github.com/usaybia/usaybia-data/releases) that has an asset with the same filename as the one the workflow is trying to create. You can ignore this error--the important thing is whether your other steps work.
- [x] Once this is all working, copy the new steps and conditionals from release-dev.yml to release.yml (this is to enable it for the master branch)
- [x] delete the test-version.yml workflow
- [x] create pull request from issue-82-test-version branch to development
- [x] @nathangibson will delete issue-82-test-version from https://github.com/usaybia/usaybia-data/blob/396871cef3c49f17ff6ddcb006899fc88e0c59be/.github/workflows/release-dev.yml#L9  

You can let me know any questions here in the issue.

**Comment by hannafriedel** [comment]
Hi Nathan, in the first step you tagged a line of code in the branch 396871cef3. Should I work in this branch or continue in issue-82-test-version branch?

**Comment by nathangibson** [comment]
@hannafriedel Great work!
