### ISSUE TITLE
Add Arabic names for transliterated LHOM names

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#95]
@hannafriedel Do you have an Arabic keyboard installed? You'll need one for this ...

Many of our person records (e.g. https://usaybia.net/person/1) do not have Arabic-script names, only transliteration. Eventually we will get more Arabic names from the tagging but we want to help the tagging process be more automatic by gathering at least the common names in Arabic script. 

In [this spreadsheet, the "Names" tab/sheet](https://docs.google.com/spreadsheets/d/1ujiT91ua3sA-WX86OWpuE-gDD_E-zONpI1dP70pXdWw/edit#gid=1890174451), there is a list of transliterated names or parts of names (column A), sorted by most frequent to least frequent. Then there is a column (C) for the Arabic-script equivalent. 

Example:
Arabic (LHOM) |
-- | 
محمد | 

In Arabic (LHOM) please copy or type the Arabic name **as it typically appears in the LHOM edition**. Column E automatically pulled an example of a person who might have that name (but if you see `#N/A` that means we don't have one). If so, you can copy it exactly as it appears there. Columns F+ split the example into parts so that you can easily copy one name from it. 

Example | Example Split |   |   |   |  
-- | -- | -- | -- | -- | --
أبو العرب يوسف بن محمد | أبو | العرب | يوسف | بن | محمد

If there is no example and the name/word is ambiguous, you can assume the LHOM name has no vocalization except for أ/إ/آ at the beginning of a word/syllable. An ambiguous word would be one like Malik, which LHOM might have vocalized since it might also be the word mulk. So in such cases, if there's no example, you'll need to find an example in LHOM. In principle you can search at https://dh.brill.com/scholarlyeditions/reader/urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-tr-eng1:10.64/?right=lhom-ed-ara1 though sometimes the search doesn't work properly.

In Column D please put your initials (HF) on the rows you've done.

Please do all the ones that have at least 5 occurrences (about 200 rows) and then we'll evaluate whether it's helpful to do more. 

Thanks! And let me know here in the issue if you have questions. Or if it's about a specific item in the spreadsheet you can tag me in a comment there.

**Comment by hannafriedel** [comment]
Hi Nathan, I don't quite understand how the search works. It fails me and doesn't find anything. I don't know if that's because of me or the search engine.

**Comment by nathangibson** [comment]
Ya, I’ve been having trouble with it the last couple days too. Anyway, you could just do the ones that have examples in the spreadsheet you can copy from.

**Comment by hannafriedel** [comment]
I'm done. I have a few empty spaces left. For some, I just couldn't find something. For some I have a guess what might have happened, details below.

- I suspect that row 58 (Alāʾ) and 72 (Asad) might be typos, because I couldn't find those names, but instead got results for ʿAlāʾ and Asʿad.
- row 114 (Kay) i could find Kay only once in the English translation [in 4.1.5]. It is used by the editors to shorten the name of a king. The "Kay" part doesn't have an equivalent in the arabic text.

**Comment by nathangibson** [comment]
OK, thanks! I'll do the ones you mentioned. 

Please continue with all the ones that have at least 2 occurrences.

**Comment by hannafriedel** [comment]
I'm done :)

- row 202 "John" only appears in translation: The arabic name is يحيى النحوي
- row 368 "Baldwin" is only in the translation. In arabic he is only reference as "he" and "the kings son"

**Comment by nathangibson** [comment]
@hannafriedel Sorry, it looks like I accidentally missed a bunch of names including some common ones. Maybe they got cut off when I copied and pasted. 

I've put the new ones at row 1078 and below, under your previous list. Could you please do all the ones with 2+ occurrences (about 450)?

**Comment by hannafriedel** [comment]
will do, no worries, I was already confused why there were so few names.

**Comment by nathangibson** [comment]
@hannafriedel Great! Once you're done with that, you can go on to #96.

**Comment by nathangibson** [comment]
>     * I suspect that row 58 (Alāʾ) and 72 (Asad) might be typos, because I couldn't find those names, but instead got results for ʿAlāʾ and Asʿad.
- 58, yes, you're correct
- 72 Actually although Asʿad is more common, there is also a name أسد (see https://ar.wikipedia.org/wiki/%D8%A3%D8%B3%D8%AF_%D8%A8%D9%86_%D8%B3%D8%A7%D9%85%D8%A7%D9%86) Since it is only mentioned in an English note, there are no hits in the Arabic text.

**Comment by nathangibson** [comment]
>     * row 114 (Kay) i could find Kay only once in the English translation [in 4.1.5]. It is used by the editors to shorten the name of a king. The "Kay" part doesn't have an equivalent in the arabic text.

It is used for some Persian kings and for some Seljuq sultans. In one case (person/447) the LHOM editors weren't consistent--it should be `ʿAlāʾ al-Dīn Kayqubādh` instead of `ʿAlāʾ al-Dīn Kay-Qubādh` - I've changed it now in the English and in the Arabic for him. In another case, it is Kay Bahman, but the "Kay" doesn't occur in the Arabic, as you say, so we can just leave the "Kay" Arabic equivalent blank and I just put بهمن in the Text spreadsheet for his Arabic name.

**Comment by nathangibson** [comment]
>     * row 202 "John" only appears in translation: The arabic name is يحيى النحوي

There are various Arabic equivalents for "John" including يحيى , so we have to handle these individually (please leave the John equivalent blank). In the record for John the Grammarian (in the Text sheet) I've added the Arabic.

**Comment by nathangibson** [comment]
>     * row 368 "Baldwin" is only in the translation. In arabic he is only referenced as "he" and "the kings son"

I've added بلدوين from Wikipedia. This isn't what we normally want to do, but it's good to provide some kind of Arabic equivalent even if we can't get it from the LHOM text.

**Comment by hannafriedel** [comment]
Hi Nathan, thank you or filling in the holes I left. I had some problems with the new names as well:

- row 1088: "bar" is only part of an alternativ name mentioned in the translation (see 9.39).
- row 1124: I couldn't find "Azd", only al-Azdī
- row 1156: "younger" there are at least two alternatives: قريب and ثاني should I just leave it open as with John?
- row 1178: "elder" same problem
- row 1160: "Ṭalib" I think that might be a typo by the translator. I only found it once and even then the arabic equivalent was طالب
- row 1230: "[ibn" looks as if bracket was interpreted as part of a name. I put down بن 
- row 1268: "see" I don't think, that that is part of a name, the search function didn't provide answers either

**Comment by hannafriedel** [comment]
I'm done now and will continue with issue 96.

**Comment by nathangibson** [comment]
Awesome! I'll close this issue once I address the remaining issues you mentioned.
