### ISSUE TITLE
Machine-assisted name tagging

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#98]
Hi @wsalesky ,
I'm trying to figure out how to speed up some of our person and place name tagging in our XML source texts, and I'd love your input on what the most streamlined thing to implement would be.

Our workflow right now is that someone reads the text and tags names with persName or placeName in VS Code (or Oxygen is also possible), but then has to search Usaybia for the URI to put in the `@ref`. We've been able to use some regex to semi-successfully find names based on patterns and wrap them with a persName tag, but the URI searching is still time-consuming. 

1. [Eeditiones has created an awesome VS Code plugin](https://e-editiones.org/vscode/) that searches for your selected text in various authorities and you can click on a result to tag it. I assume we could fork this, but we'd have to enable the API like you've done for Syriaca and then write a simple (?) connector like this https://github.com/eeditiones/tei-publisher-vscode/blob/master/src/connectors/gnd.ts. How much effort would this take you?
2. I remember you had NER set up at one point in Srophe. How does it work, and is it a likely possibility? Keep in mind that Arabic names are _very_ fluid in terms of which part of the name they use (eg the person Abu al-Faraj Abd Allah ibn al-Tayyib might appear as Abu al-Faraj or Ibn al-Tayyaib). So it would need to be something that could prioritize hits on multiple parts of a name without being thrown off by other parts that don't match or are missing. 

Thoughts? 

One possibility would be for us to manually curate URIs on names for the chapters we have time to deal with in depth and use NER to tag multiple possibilities on the ones we don't have time for.

**Comment by wsalesky** [comment]
@nathangibson 
1. Very cool, I had not heard of this plugin. I think it would be fairly painless to get it running with Usaybia. Currently the REST API is down on Usaybia, but it should be a simple fix, I will take a look at it. Once the REST API is running those queries should run out of the box. We will have to see if the data returned is in the correct format, but that would be a minor fix. 
2. I will have to go back and look at the NER processor, I'm not sure it is as robust as the VS Code plugin. I believe it is built in XQuery, and uses the eXist-db full text search to find matches. I will take a look at the code and get back to you.

**Comment by nathangibson** [comment]
@wsalesky 
1. Nice! The VSC plugin would majorly improve our efficiency. Since you think it's pretty straightforward, let's go ahead and try that. Do you think it would make sense to first fork it in the srophe org and add a connector to the (currently working) Syriaca URI, so that it's available to all srophe users, then we could fork that for Usaybia? If so, I think you could go ahead and do that. I'll make a couple of issues.
2. If we do 1., the NER is a lower priority but would still be interesting. Actually, on further reflection, I think it could be a lot more helpful for place names, which are quite consistent in our text, than for person names. I'll make an issue for this as well.
